"""TypedDict models for structured output types.

All TypedDicts use ``total=False`` to match existing ``.get()`` guard
patterns throughout the codebase.  This is consistent with the convention
established in ``openapi_types.py``.

These types provide static type annotations with zero runtime overhead -
TypedDict is a dict at runtime, so no serialization round-trip is needed.
"""

from dataclasses import dataclass
from typing import Any, TypedDict


@dataclass
class ToolCustomization:
    """Startup-time metadata carried from customize phase to runtime transforms.

    Replaces the ad-hoc ``dict`` previously stored at
    ``component.meta["_customization"]``.  Every field that the runtime
    wrapping pipeline, label transform, or text-response handler reads
    is declared here as an explicit typed attribute.

    All fields have defaults so tests can construct partial instances
    and mutate fields after construction.  Production code in
    ``_customize_metadata`` always sets every field explicitly.
    """

    has_labels: bool = False
    is_text_response: bool = False
    is_empty_response: bool = False
    is_binary_response: bool = False
    route_path: str = ""
    route_method: str = ""
    response_transform: str | None = None


class ViewHints(TypedDict, total=False):
    """Resolved display-view hints for one response type.

    The agent-facing markdown collection view derives its field set from the
    response schema; this carries the converter's curated *deficiencies*
    (``openapi_converter/display_hints.py``) alongside the other
    registration-time display metadata.  It travels in ``tool.meta`` for
    autogenerated tools and in resource content meta for resources, next to
    ``response_type`` / ``output_schema_raw``.

    The value is a plain ``dict`` at runtime (a TypedDict), so it survives
    meta serialization unchanged and consumers never meet two shapes.  Keys
    mirror the curated tables:

    - ``omit`` — property names to drop from the collection view.
    - ``compact`` — property name -> identity field to read from the nested
      object, or ``None`` for the generic identity policy.
    - ``flag`` — property names to render as a boolean flag (``Yes``/``No``).
    """

    omit: list[str]
    compact: dict[str, str | None]
    flag: list[str]


class ToolSearchEntry(TypedDict, total=False):
    """A compact tool entry returned from ``search_tools`` and ``search``.

    ``score`` is the normalized relevance (0.0-1.0) for the query that
    produced this entry; 1.0 is the top match.
    """

    name: str
    description: str
    tags: list[str]
    annotations: dict[str, Any]
    score: float


class ResourceEntry(TypedDict, total=False):
    """A resource entry returned from ``list_resources`` and ``search_resources``.

    The ``type`` field is accessed via ``entry["type"]`` rather than
    ``entry.type`` to avoid shadowing the Python built-in.  This follows
    the same pattern as ``param["in"]`` in ``OpenAPIParameter``.
    """

    uri: str
    name: str
    description: str
    mimeType: str
    type: str  # "resource" or "template"; accessed via ["type"]
    tags: list[str]
    required_scope: str | None
    optional_params: list[dict[str, Any]] | None
    size_hint: str | None
    default_detail: str | None


class ResourceListing(TypedDict, total=False):
    """Top-level response from ``list_resources``."""

    resources: list[ResourceEntry]
    count: int


class DocEntry(TypedDict, total=False):
    """A workflow guide entry returned from ``search_docs``."""

    name: str
    title: str
    description: str
    tags: list[str]


class UnifiedSearchItem(TypedDict, total=False):
    """A single merged result from the unified ``search`` tool.

    The ``type`` field discriminates between ``"tool"``, ``"doc"``,
    and ``"resource"`` results.  It is accessed via ``entry["type"]``
    (same reasoning as ``ResourceEntry.type``).

    ``score`` is the normalized relevance (0.0-1.0) for the query that
    produced this item; 1.0 is the top match.
    """

    type: str  # "tool", "doc", or "resource"; accessed via ["type"]
    name: str
    description: str
    tags: list[str]
    access_uri: str
    uri: str
    title: str
    score: float


class ToolSchemaResult(TypedDict, total=False):
    """Full tool schema returned from ``tool_info``."""

    name: str
    description: str
    parameters: dict[str, Any]
    output_example: Any
    output_schema: dict[str, Any]
    annotations: dict[str, Any]
    tags: list[str]
    version: str


class SimpleStringResult(TypedDict, total=False):
    """Simple ``{"result": str}`` shape used by ``read_doc``, ``read_resource``, etc."""

    result: str


__all__ = [
    "DocEntry",
    "ResourceEntry",
    "ResourceListing",
    "SimpleStringResult",
    "ToolCustomization",
    "ToolSchemaResult",
    "ToolSearchEntry",
    "UnifiedSearchItem",
    "ViewHints",
]
