"""Typed registration records for exposed tools and registered resources.

Registration metadata was historically multiplexed across ad-hoc ``meta`` dict
keys, written on several paths (autogen vs synthetic, tool vs resource) and
partly completed later.  A field set on one path but read on another surfaces
only as a surprise at call time.  This module is the single contract:

- :class:`ToolRegistration` — the complete record carried by every wrapped
  tool, under ``meta[REGISTRATION_KEY]``.
- :class:`ResourceRegistration` — the record carried by every registered
  resource, under the same key.
- :func:`get_tool_registration` / :func:`get_resource_registration` — the
  sanctioned accessors.  Runtime code reads registration metadata through
  them; it never subscripts a registration key directly.
- :func:`build_content_meta` / :func:`parse_content_meta` — the typed helpers
  for the resource *content* metadata channel (read-time display metadata,
  distinct from registration metadata).

The record is a plain JSON-native dict on the wire and is reconstructed as a
dataclass by the accessors, so it survives FastMCP's pydantic meta
serialisation and never carries a callable (an executor lives in the per-server
registry, referenced by the serializable ``executor_id``).

``ToolRegistration.virtual_params`` is ``None`` until virtual-param injection
has run; :meth:`ToolRegistration.with_injected` produces the finalised record.
The finalisation happens once per tool at the exposure seam
(``_ToolWrappingTransform._wrap``), before any tool is listed or called.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, replace
from typing import TYPE_CHECKING, Any

from gitea_mcp_server.models import ToolCustomization, ViewHints

if TYPE_CHECKING:
    from collections.abc import Iterable

REGISTRATION_KEY = "registration"
"""The single sanctioned ``meta`` key carrying a registration record."""

RETIRED_TOOL_META_KEYS: frozenset[str] = frozenset(
    {
        "_contract_wrap",
        "_synthetic",
        "_executor_id",
        "_virtual_params",
        "_customization",
        "output_schema_raw",
        "response_type",
        "view_hints",
    }
)
"""Flat registration keys retired by the record contract.

Phase 2 asserts none of these remain on an exposed component; Phase 3 adds a
static guard against reintroduction.  They are the runtime denylist, not a
positive whitelist of ``meta`` (FastMCP owns other keys).
"""

RETIRED_RESOURCE_META_KEYS: frozenset[str] = frozenset(
    {
        "required_scopes",
        "cache_ttl",
        "optional_params",
        "size_hint",
        "default_detail",
    }
)
"""Flat resource-registration keys retired by the record contract."""

CONTENT_META_KEYS: frozenset[str] = frozenset(
    {"response_schema", "format_hint", "response_type", "view_hints"}
)
"""Known resource *content* metadata keys (read-time display metadata).

Everything else in a content meta dict is formatter context (``owner``,
``repo``, ``type``, ``ref``, ...), forwarded to the display pipeline as
``extra``.
"""


@dataclass
class ToolRegistration:
    """The complete registration record for one exposed tool.

    Built by the registration site (:func:`for_autogen` / :func:`for_synthetic`
    / :func:`for_proxy`) and finalised at the exposure seam, where the injected
    virtual-param set is known.  ``virtual_params`` distinguishes the two
    injection intents, which must not be conflated:

    - ``virtual_param_allowlist is None`` — autogen: inject every visible
      registry param, never shadowing a real API parameter (``inject_into``'s
      ``only=None`` behaviour).
    - ``virtual_param_allowlist`` set — synthetic: inject exactly these names,
      overwriting any same-named declared parameter with the registry schema.
    """

    wrap: bool = False
    synthetic: bool = False
    virtual_params: frozenset[str] | None = None
    virtual_param_allowlist: frozenset[str] | None = None
    executor_id: str | None = None
    customization: ToolCustomization | None = None
    output_schema_raw: dict[str, Any] | None = None
    response_type: str | None = None
    view_hints: ViewHints | None = None

    @classmethod
    def for_autogen(
        cls,
        *,
        customization: ToolCustomization,
        output_schema_raw: dict[str, Any] | None,
        response_type: str | None,
        view_hints: ViewHints | None,
    ) -> ToolRegistration:
        """Build the pending record for an autogenerated tool.

        ``virtual_params`` is left ``None`` until injection runs at exposure;
        the allowlist is ``None`` (autogen injection intent).
        """
        return cls(
            wrap=True,
            synthetic=False,
            customization=customization,
            output_schema_raw=output_schema_raw,
            response_type=response_type,
            view_hints=view_hints,
        )

    @classmethod
    def for_synthetic(
        cls,
        *,
        executor_id: str,
        allowlist: Iterable[str],
    ) -> ToolRegistration:
        """Build the pending record for a wrapped synthetic tool.

        The allowlist is known at registration; ``virtual_params`` is resolved
        by injection at exposure.
        """
        return cls(
            wrap=True,
            synthetic=True,
            executor_id=executor_id,
            virtual_param_allowlist=frozenset(allowlist),
        )

    @classmethod
    def for_proxy(cls) -> ToolRegistration:
        """Build the finalised record for an unwrapped passthrough (``call_tool``)."""
        return cls(wrap=False, synthetic=False, virtual_params=frozenset())

    def is_finalised(self) -> bool:
        """Return ``True`` once virtual-param injection has resolved the record."""
        return self.virtual_params is not None

    def with_injected(self, injected: Iterable[str]) -> ToolRegistration:
        """Return a finalised copy with the resolved virtual-param set."""
        return replace(self, virtual_params=frozenset(injected))

    def validate(self) -> list[str]:
        """Return the ways this record is incomplete; empty means complete.

        The required-field matrix is per kind (autogen / synthetic / proxy).
        Never raises — callers decide how to fail.
        """
        problems: list[str] = []
        if self.virtual_params is None:
            problems.append("virtual_params not finalised (injection not applied)")
        if self.wrap:
            if self.synthetic:
                if not self.executor_id:
                    problems.append("synthetic record missing executor_id")
                if not self.virtual_param_allowlist:
                    problems.append("synthetic record missing virtual_param_allowlist")
            else:
                if self.executor_id is not None:
                    problems.append("autogen record must not carry executor_id")
                if self.customization is None:
                    problems.append("autogen record missing customization")
        else:
            if self.synthetic:
                problems.append("proxy record must not be synthetic")
            if self.executor_id is not None:
                problems.append("proxy record must not carry executor_id")
        return problems

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-native dict (frozensets become sorted lists)."""
        return {
            "wrap": self.wrap,
            "synthetic": self.synthetic,
            "virtual_params": (
                None if self.virtual_params is None else sorted(self.virtual_params)
            ),
            "virtual_param_allowlist": (
                None
                if self.virtual_param_allowlist is None
                else sorted(self.virtual_param_allowlist)
            ),
            "executor_id": self.executor_id,
            "customization": asdict(self.customization) if self.customization else None,
            "output_schema_raw": self.output_schema_raw,
            "response_type": self.response_type,
            "view_hints": self.view_hints,
        }

    @classmethod
    def from_dict(cls, data: Any) -> ToolRegistration:
        """Rebuild a record from its dict form (total over a record instance too)."""
        if isinstance(data, cls):
            return data
        customization = data.get("customization")
        if isinstance(customization, ToolCustomization):
            custom = customization
        elif isinstance(customization, dict):
            custom = ToolCustomization(**customization)
        else:
            custom = None
        virtual_params = data.get("virtual_params")
        allowlist = data.get("virtual_param_allowlist")
        return cls(
            wrap=bool(data.get("wrap", False)),
            synthetic=bool(data.get("synthetic", False)),
            virtual_params=None if virtual_params is None else frozenset(virtual_params),
            virtual_param_allowlist=None if allowlist is None else frozenset(allowlist),
            executor_id=data.get("executor_id"),
            customization=custom,
            output_schema_raw=data.get("output_schema_raw"),
            response_type=data.get("response_type"),
            view_hints=data.get("view_hints"),
        )


@dataclass
class ResourceRegistration:
    """The complete registration record for one registered resource.

    ``size_hint`` and ``default_detail`` are required — every registration path
    derives or declares them.  ``cache_ttl`` is deliberately absent: the
    response cache reads TTLs from the resource surface
    (``resources/surface.py``), the single source of that fact.
    """

    size_hint: str = ""
    default_detail: str = ""
    required_scopes: list[str] | None = None
    optional_params: list[dict[str, Any]] | None = None

    def validate(self) -> list[str]:
        """Return the ways this record is incomplete; empty means complete."""
        problems: list[str] = []
        if not self.size_hint:
            problems.append("resource record missing size_hint")
        if not self.default_detail:
            problems.append("resource record missing default_detail")
        return problems

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-native dict, omitting unset optional fields."""
        result: dict[str, Any] = {
            "size_hint": self.size_hint,
            "default_detail": self.default_detail,
        }
        if self.required_scopes is not None:
            result["required_scopes"] = self.required_scopes
        if self.optional_params is not None:
            result["optional_params"] = self.optional_params
        return result

    @classmethod
    def from_dict(cls, data: Any) -> ResourceRegistration:
        """Rebuild a record from its dict form (total over a record instance too)."""
        if isinstance(data, cls):
            return data
        return cls(
            size_hint=data.get("size_hint", ""),
            default_detail=data.get("default_detail", ""),
            required_scopes=data.get("required_scopes"),
            optional_params=data.get("optional_params"),
        )


def get_tool_registration(tool: Any) -> ToolRegistration | None:
    """Return *tool*'s registration record, or ``None`` when unregistered."""
    raw = (getattr(tool, "meta", None) or {}).get(REGISTRATION_KEY)
    return ToolRegistration.from_dict(raw) if raw is not None else None


def get_resource_registration(resource: Any) -> ResourceRegistration | None:
    """Return *resource*'s registration record, or ``None`` when unregistered."""
    raw = (getattr(resource, "meta", None) or {}).get(REGISTRATION_KEY)
    return ResourceRegistration.from_dict(raw) if raw is not None else None


def set_registration(component: Any, record: ToolRegistration | ResourceRegistration) -> None:
    """Store *record* on *component* under the single sanctioned meta key."""
    meta = component.meta
    if meta is None:
        meta = {}
        component.meta = meta
    meta[REGISTRATION_KEY] = record.to_dict()


def build_content_meta(
    *,
    response_schema: dict[str, Any] | None = None,
    format_hint: str | None = None,
    response_type: str | None = None,
    view_hints: ViewHints | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any] | None:
    """Build a resource content-meta dict from known keys + formatter context.

    Returns ``None`` when there is nothing to carry (the ``or None`` idiom
    used throughout the display path).
    """
    meta: dict[str, Any] = {}
    if response_schema is not None:
        meta["response_schema"] = response_schema
    if format_hint is not None:
        meta["format_hint"] = format_hint
    if response_type is not None:
        meta["response_type"] = response_type
    if view_hints is not None:
        meta["view_hints"] = view_hints
    if extra:
        meta.update(extra)
    return meta or None


def parse_content_meta(
    meta: dict[str, Any] | None,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    """Split content meta into known display keys and formatter ``extra``.

    Returns ``(known, extra)``; each is ``None`` when empty.
    """
    known: dict[str, Any] = {}
    extra: dict[str, Any] = {}
    for key, value in (meta or {}).items():
        if key in CONTENT_META_KEYS:
            known[key] = value
        else:
            extra[key] = value
    return known or None, extra or None


__all__ = [
    "CONTENT_META_KEYS",
    "REGISTRATION_KEY",
    "RETIRED_RESOURCE_META_KEYS",
    "RETIRED_TOOL_META_KEYS",
    "ResourceRegistration",
    "ToolRegistration",
    "build_content_meta",
    "get_resource_registration",
    "get_tool_registration",
    "parse_content_meta",
    "set_registration",
]
