"""URI template utility functions.

Flat infrastructure module — no domain dependencies.  Provides helpers for
working with RFC 6570 URI templates used across the resource registration,
tool, and display layers.

Path placeholders
-----------------
:func:`iter_path_params` / :func:`path_param_names` are the **single
path-placeholder parser**.  They recognize ``{param}`` and ``{param*}``,
including kebab-case names (``{repository-id}``), and deliberately do **not**
match an RFC 6570 ``{?a,b}`` query suffix — that is a separate grammar, still
handled by :func:`clean_resource_uri` (``\\{\\?[^}]+\\}$``),
:func:`expand_path_params` (partition on ``{?``), and FastMCP.  Do not claim a
single *URI* placeholder contract while that second grammar lives on.

The parser is **structural**: it reports names in template form (original
spelling preserved).  The normalized↔wire rename mapping is the spec's
``x-param-rename`` contract (``gitea_mcp_server.param_rename``), read by both
the tool and resource surfaces — not derived from the placeholder names.

Percent-encoding
----------------
Path parameter values are percent-encoded when substituted into a URI or an
API path via :func:`expand_path_params`, a thin wrapper over FastMCP's
``expand_uri_template`` (the framework's documented inverse of
``match_uri_template``).  A simple ``{param}`` segment encodes ``/``
(``quote(value, safe="")``) and a wildcard ``{param*}`` segment preserves it
(``quote(value, safe="/")``), so a substituted value round-trips through
FastMCP unchanged.  Delegating also gives hyphen→underscore alias resolution
(``{repository-id}`` ↔ ``repository_id``) for free.

Deliberate omission: values are **not** dot-encoded.  FastMCP's
``RequestDirector._build_url`` encodes ``.`` as ``%2E`` for autogenerated tool
paths (path-traversal/SSRF hardening); ``expand_uri_template`` mirrors the
*resource matcher* instead, which does not.  Encoding dots here would change
the wire form for dotted names (``foo.bar`` → ``foo%2Ebar``) for no behavior
gain in the current charset — explicitly out of scope for #736.

This is the single home for that contract.  Audited substitution sites
(issue #736):

- ``server_setup.mcp_builder._boolean_check_resource_uri`` — encoded via
  :func:`expand_path_params`; the derived URI is read back through FastMCP's
  resource matcher.
- ``resources.factory.make_api_resource``'s generated handler — encoded via
  :func:`expand_path_params`; the API path is sent to Gitea through httpx.
- ``cache_invalidation._substitute_template`` — deliberately **raw**: cache
  keys are canonicalised (percent-decoded once, path only) by
  ``response_cache`` so a read spelled raw or percent-encoded is one entry,
  and raw substitution from tool arguments reproduces that canonical form.
- ``label_service`` error text and ``tools.unified_search`` guide
  ``access_uri`` — display strings built from validated names / internal
  catalog slugs, never fetched.
- Query parameters are never string-concatenated: they travel via httpx
  ``params=`` and are encoded there.  FastMCP's ``RequestDirector`` likewise
  encodes autogenerated-tool path parameters before building the URL.
"""

import re
from collections.abc import Iterator, Mapping
from typing import Any

from fastmcp.resources.template import expand_uri_template

# A path placeholder: ``{param}`` or ``{param*}``.  The name charset includes
# ``-`` so kebab-case placeholders (``{repository-id}``) are recognized — the
# route template keeps the original wire spelling while Rule A renames the
# parameter *definition* to snake_case (see ``openapi_converter.normalize``).
# An RFC 6570 ``{?a,b}`` query suffix is deliberately **not** matched: it is a
# different grammar (see the module docstring).
_PATH_PARAM_RE = re.compile(r"\{([\w-]+)(\*)?\}")


def iter_path_params(template: str) -> Iterator[tuple[str, bool]]:
    """Yield ``(name, is_wildcard)`` for each path placeholder in a template.

    Names are in **template form** — the original spelling is preserved
    (``{repository-id}`` yields ``"repository-id"``, not ``"repository_id"``).
    The normalized↔wire mapping is the spec's ``x-param-rename`` contract, not
    this parser's concern.

    Args:
        template: A URI or API-path template.

    Yields:
        ``(name, is_wildcard)`` in template order.
    """
    for match in _PATH_PARAM_RE.finditer(template):
        yield match.group(1), match.group(2) is not None


def path_param_names(template: str) -> list[str]:
    """Return the path-placeholder names in a template, order-preserving.

    Template-form names (hyphens preserved).  A ``{?a,b}`` query suffix is not
    a path placeholder and is not returned.

    Args:
        template: A URI or API-path template.

    Returns:
        The path-param names (e.g. ``["owner", "repo", "repository-id"]``).
    """
    return [name for name, _ in iter_path_params(template)]


def clean_resource_uri(uri: str) -> str:
    """Strip RFC 6570 form-style query parameters from a resource URI.

    Resource templates use ``{?param}`` syntax internally so FastMCP routes
    query-string parameters to the handler.  This function returns the base
    URI without ``{?param}`` suffixes:

    - For display: show a clean template without parameter noise — agents
      discover available optional parameters via ``optional_params`` metadata.
    - For skip-set normalization: custom resources register with suffixes
      (e.g. ``gitea://repos/{owner}/{repo}/issues{?state,type}``) while
      auto-generated resources build URIs from spec paths alone
      (``gitea://repos/{owner}/{repo}/issues``).  Stripping suffixes on
      both sides ensures they match.

    Example:
        ``gitea://repos/{owner}/{repo}/issues{?state}`` →
        ``gitea://repos/{owner}/{repo}/issues``

    Note:
        The regex only strips ``{?...}`` when it appears at the **end** of the
        URI (``$`` anchor).  This assumes query params are always the last
        segment in a URI template — a convention enforced by convention, not
        code.  If a future URI template places ``{?param}`` before trailing
        path segments, this function must be updated.

    Args:
        uri: The raw URI template.

    Returns:
        Cleaned URI with ``{?...}`` suffix removed.
    """
    return re.sub(r"\{\?[^}]+\}$", "", uri)


def wildcard_param_names(uri_template: str) -> set[str]:
    """Return the names of ``{param*}`` wildcard segments in a URI template.

    Args:
        uri_template: The URI template (e.g.
            ``gitea://repos/{owner}/{repo}/contents/{filepath*}``).

    Returns:
        The set of wildcard parameter names (e.g. ``{"filepath"}``).
    """
    return {name for name, is_wildcard in iter_path_params(uri_template) if is_wildcard}


def render_wildcard_segment(uri: str, param: str) -> str:
    """Render ``{param}`` as ``{param*}`` in a URI template, segment-aware.

    Only a path segment that is *exactly* ``{param}`` becomes ``{param*}``.
    A plain ``str.replace`` would also rewrite a same-named substring inside
    a different segment (e.g. ``{filepath}`` inside ``{filepath2}``) or a
    ``{?query}`` suffix — both wrong.  Path params are always full segments
    (between ``/``), so splitting on ``/`` is the correct boundary.

    Args:
        uri: The URI template (e.g. ``gitea://repos/{owner}/{repo}/contents/{filepath}``).
        param: The wildcard param name (e.g. ``"filepath"``).

    Returns:
        The URI with the exact ``{param}`` segment rendered ``{param*}``.
    """
    segments = uri.split("/")
    rendered = [seg if seg != f"{{{param}}}" else f"{{{param}*}}" for seg in segments]
    return "/".join(rendered)


def expand_path_params(template: str, params: Mapping[str, Any]) -> str:
    """Substitute path parameters into a URI/path template, percent-encoding values.

    Thin wrapper over FastMCP's ``expand_uri_template`` (the framework's
    documented inverse of ``match_uri_template``), kept so this module remains
    the single, swappable home for the encoding contract and its audit.
    ``{param}`` matches one segment and encodes ``/``; ``{param*}`` (wildcard)
    preserves ``/`` so multi-segment values (file paths) route as separators.
    Placeholders with no matching key are left untouched.  Values are
    percent-encoded before substitution, so a value containing ``{name}`` is
    never re-expanded.

    An RFC 6570 ``{?query}`` suffix is preserved verbatim and never expanded —
    this is a *path* substituter, and query parameters travel via httpx
    ``params=``, never string concatenation.

    Args:
        template: URI or API-path template with ``{param}``/``{param*}``
            placeholders.
        params: Parameter values keyed by placeholder name.  Extra keys are
            ignored.

    Returns:
        The template with every resolvable path placeholder substituted.
    """
    path_part, query_marker, query_rest = template.partition("{?")
    return expand_uri_template(path_part, dict(params)) + query_marker + query_rest


__all__ = [
    "clean_resource_uri",
    "expand_path_params",
    "iter_path_params",
    "path_param_names",
    "render_wildcard_segment",
    "wildcard_param_names",
]
