"""URI template utility functions.

Flat infrastructure module — no domain dependencies.  Provides helpers for
working with RFC 6570 URI templates used across the resource registration,
tool, and display layers.

Percent-encoding
----------------
Path parameter values are percent-encoded when substituted into a URI or an
API path.  The encoding is the exact inverse of FastMCP's resource matcher
(``fastmcp.resources.template.match_uri_template``), which ``unquote``s
captured groups: a simple ``{param}`` segment encodes ``/``
(``quote(value, safe="")``) and a wildcard ``{param*}`` segment preserves it
(``quote(value, safe="/")``).  A substituted value therefore round-trips
through FastMCP unchanged.

This is the single home for that contract.  Audited substitution sites
(issue #736):

- ``server_setup.mcp_builder._boolean_check_resource_uri`` — encoded via
  :func:`expand_path_params`; the derived URI is read back through FastMCP's
  resource matcher.
- ``resources.factory.make_api_resource``'s generated handler — encoded via
  :func:`expand_path_params`; the API path is sent to Gitea through httpx.
- ``cache_invalidation._substitute_template`` — deliberately **raw**: cache
  keys are canonicalised (percent-decoded) by ``response_cache`` so a read
  spelled raw or percent-encoded is one entry, and raw substitution from tool
  arguments reproduces that canonical form.
- ``label_service`` error text and ``tools.unified_search`` guide
  ``access_uri`` — display strings built from validated names / internal
  catalog slugs, never fetched.
- Query parameters are never string-concatenated: they travel via httpx
  ``params=`` and are encoded there.  FastMCP's ``RequestDirector`` encodes
  path parameters for autogenerated tools the same way.
"""

import re
from collections.abc import Mapping
from typing import Any
from urllib.parse import quote

# ``{param*}`` — a wildcard path parameter that may span ``/``.
_WILDCARD_PARAM_RE = re.compile(r"\{(\w+)\*\}")
# ``{param}`` / ``{param*}`` — a path placeholder.  Does not match the
# ``{?a,b}`` query suffix (the ``?`` follows the opening brace).
_PATH_PARAM_RE = re.compile(r"\{(\w+)(\*)?\}")


def clean_resource_uri(uri: str) -> str:
    """Strip RFC 6570 form-style query parameters from a resource URI.

    Resource templates use ``{?param}`` syntax internally so FastMCP routes
    query-string parameters to the handler.  This function returns the base
    URI without ``{?param}`` suffixes:

    - For display: show a clean template without parameter noise — agents
      discover available optional parameters via ``optional_params`` metadata.
    - For skip-set normalization: custom resources register with suffixes
      (e.g. ``gitea://repos/{owner}/{repo}/issues{?state,type}``) while
      auto-generated resources build URIs from spec paths alone
      (``gitea://repos/{owner}/{repo}/issues``).  Stripping suffixes on
      both sides ensures they match.

    Example:
        ``gitea://repos/{owner}/{repo}/issues{?state}`` →
        ``gitea://repos/{owner}/{repo}/issues``

    Note:
        The regex only strips ``{?...}`` when it appears at the **end** of the
        URI (``$`` anchor).  This assumes query params are always the last
        segment in a URI template — a convention enforced by convention, not
        code.  If a future URI template places ``{?param}`` before trailing
        path segments, this function must be updated.

    Args:
        uri: The raw URI template.

    Returns:
        Cleaned URI with ``{?...}`` suffix removed.
    """
    return re.sub(r"\{\?[^}]+\}$", "", uri)


def wildcard_param_names(uri_template: str) -> set[str]:
    """Return the names of ``{param*}`` wildcard segments in a URI template.

    Args:
        uri_template: The URI template (e.g.
            ``gitea://repos/{owner}/{repo}/contents/{filepath*}``).

    Returns:
        The set of wildcard parameter names (e.g. ``{"filepath"}``).
    """
    return set(_WILDCARD_PARAM_RE.findall(uri_template))


def render_wildcard_segment(uri: str, param: str) -> str:
    """Render ``{param}`` as ``{param*}`` in a URI template, segment-aware.

    Only a path segment that is *exactly* ``{param}`` becomes ``{param*}``.
    A plain ``str.replace`` would also rewrite a same-named substring inside
    a different segment (e.g. ``{filepath}`` inside ``{filepath2}``) or a
    ``{?query}`` suffix — both wrong.  Path params are always full segments
    (between ``/``), so splitting on ``/`` is the correct boundary.

    Args:
        uri: The URI template (e.g. ``gitea://repos/{owner}/{repo}/contents/{filepath}``).
        param: The wildcard param name (e.g. ``"filepath"``).

    Returns:
        The URI with the exact ``{param}`` segment rendered ``{param*}``.
    """
    segments = uri.split("/")
    rendered = [seg if seg != f"{{{param}}}" else f"{{{param}*}}" for seg in segments]
    return "/".join(rendered)


def expand_path_params(template: str, params: Mapping[str, Any]) -> str:
    """Substitute path parameters into a URI/path template, percent-encoding values.

    ``{param}`` matches one segment and encodes ``/``; ``{param*}`` (wildcard)
    preserves ``/`` so multi-segment values (file paths) route as separators.
    A placeholder with no matching key is left untouched, and ``{?query}``
    suffixes are unaffected — query parameters travel via httpx ``params=``,
    never string concatenation.  The encoding is the inverse of FastMCP's
    ``match_uri_template`` (which ``unquote``s captured groups), so the result
    round-trips through it unchanged.

    Args:
        template: URI or API-path template with ``{param}``/``{param*}``
            placeholders.
        params: Parameter values keyed by placeholder name.  Extra keys are
            ignored.

    Returns:
        The template with every resolvable path placeholder substituted.
    """

    def _replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in params:
            return match.group(0)
        wildcard = match.group(2) is not None
        return quote(str(params[name]), safe="/" if wildcard else "")

    return _PATH_PARAM_RE.sub(_replace, template)


__all__ = [
    "clean_resource_uri",
    "expand_path_params",
    "render_wildcard_segment",
    "wildcard_param_names",
]
