name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} work
          cd work
          git switch ${FORGEJO_HEAD_REF:-main}
      - name: build app image
        run: |
          cd work
          make docker-build-ci

  lint:
    needs: [build]
    runs-on: self-hosted
    container:
      image: gitea-mcp-server:ci
    steps:
      - name: Lint (ruff)
        run: |
          cd /app
          ruff check gitea_mcp_server

  lint-tests:
    needs: [build]
    runs-on: self-hosted
    container:
      image: gitea-mcp-server:ci
    steps:
      - name: Lint tests (ruff)
        run: |
          cd /app
          ruff check tests/

  typecheck:
    needs: [build]
    runs-on: self-hosted
    container:
      image: gitea-mcp-server:ci
    steps:
      - name: Type check (mypy)
        run: |
          cd /app
          mypy gitea_mcp_server

  typecheck-tests:
    needs: [build]
    runs-on: self-hosted
    container:
      image: gitea-mcp-server:ci
    steps:
      - name: Type check tests (mypy)
        run: |
          cd /app
          mypy tests

  test:
    needs: [build]
    runs-on: self-hosted
    container:
      image: gitea-mcp-server:ci
    steps:
      - name: Test with coverage
        run: |
          cd /app
          pytest -rs --cov=gitea_mcp_server --cov-report=xml --cov-report=term-missing
