"""Registration completeness over the committed spec fixture (issue #801, Phase 1).

Every exposed tool and every registered resource must carry a complete record
(``validate() == []``).  The surface is enumerated **post-transform** — built
with ``enable_lazy_loading=False`` so ``list_tools()`` returns the full
autogen + synthetic surface, and with lazy loading on for the pinned synthetic
surface (which the search transform otherwise hides).

The fixture is the committed ``tests/swagger.v1.json``; the real spec is a
converter input, not a test dependency (the root ``swagger.v1.json`` is
gitignored — see #806).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import pytest
import respx

from gitea_mcp_server.client import GiteaClient
from gitea_mcp_server.openapi_converter import convert_swagger_to_openapi_v3
from gitea_mcp_server.openapi_converter.normalize import normalize_spec
from gitea_mcp_server.openapi_converter.param_collision import resolve_param_collisions
from gitea_mcp_server.registration import (
    RETIRED_RESOURCE_META_KEYS,
    RETIRED_TOOL_META_KEYS,
    get_resource_registration,
    get_tool_registration,
)
from gitea_mcp_server.resources.factory import derive_resource_uri
from gitea_mcp_server.resources.meta import DETAILS, SIZE_HINTS
from gitea_mcp_server.server import create_mcp_server
from gitea_mcp_server.uri_utils import clean_resource_uri
from tests.conftest import SimpleConfig

if TYPE_CHECKING:
    from fastmcp import FastMCP

    from gitea_mcp_server.openapi_types import OpenAPISpec, SwaggerV2Spec

_FIXTURE = Path(__file__).parent.parent / "swagger.v1.json"

# The synthetic tools pinned by the shared contract, in the lazy-loading-on
# configuration (``_setup_tool_discovery`` only registers the search family
# when lazy loading is enabled).
PINNED_SYNTHETIC_TOOLS = frozenset(
    {
        "search",
        "search_tools",
        "search_resources",
        "search_docs",
        "list_hidden_tools",
        "list_resources",
        "read_resource",
        "tool_info",
        "call_tool",
        "read_doc",
        "resolve_type",
    }
)

_SYNTHETIC_WHEN_LAZY_OFF = frozenset(
    {"search_docs", "read_doc", "list_resources", "read_resource", "resolve_type"}
)


async def _make_server(*, lazy: bool) -> tuple[FastMCP, str]:
    """Build a full server over the committed fixture; return (mcp, prefix)."""
    with _FIXTURE.open() as f:
        spec: dict[str, Any] = json.load(f)
    config = SimpleConfig(
        url="https://git.example.com",
        token="test_token",
        log_level="ERROR",
        tool_filtering_enabled=False,
        enable_lazy_loading=lazy,
    )
    gitea_client = GiteaClient(config)
    try:
        with respx.mock() as mock_http:
            mock_http.get("https://git.example.com/swagger.v1.json").respond(200, json=spec)
            mcp = await create_mcp_server(gitea_client)
        return mcp, (config.tool_prefix or "")
    finally:
        await gitea_client.close()


def _record_problems(tool: Any) -> list[str]:
    """Return the ways *tool*'s registration record is missing or incomplete."""
    record = get_tool_registration(tool)
    if record is None:
        return ["no registration record"]
    return record.validate()


def _converted_fixture() -> OpenAPISpec:
    """Load the committed fixture and run the production conversion pipeline.

    The raw fixture is Swagger 2.0; ``x-wildcard-path-param`` and
    ``x-param-rename`` are stamped *during* conversion, so the expected
    resource URIs must be derived from the converted spec — the same shape
    the server registers from.
    """
    with _FIXTURE.open() as f:
        raw: dict[str, Any] = json.load(f)
    spec = cast("OpenAPISpec", convert_swagger_to_openapi_v3(cast("SwaggerV2Spec", raw)))
    resolve_param_collisions(spec)
    normalize_spec(spec)
    return spec


async def _resource_uris(mcp: FastMCP) -> set[str]:
    """The registered resource URIs (concrete + templates), cleaned."""
    resources = [*await mcp.list_resources(), *await mcp.list_resource_templates()]
    uris: set[str] = set()
    for resource in resources:
        uri = getattr(resource, "uri", None) or getattr(resource, "uri_template", None)
        if uri:
            uris.add(clean_resource_uri(str(uri)))
    return uris


@pytest.mark.asyncio
async def test_every_exposed_tool_has_a_complete_record() -> None:
    """Full autogen + synthetic surface (lazy off) carries complete records."""
    mcp, _prefix = await _make_server(lazy=False)
    tools = await mcp.list_tools()
    assert tools, "expected a non-empty tool surface"
    # Guard the check against silently passing on a synthetic-only surface:
    # the lazy-off enumeration must include autogenerated tools too.
    assert any("synthetic" not in (tool.tags or []) for tool in tools), (
        "expected autogenerated tools on the lazy-off surface"
    )

    failures = {tool.name: problems for tool in tools if (problems := _record_problems(tool))}
    assert not failures, f"incomplete tool records: {failures}"


@pytest.mark.asyncio
async def test_every_registered_resource_has_a_complete_record() -> None:
    """Every concrete resource and resource template carries a complete record."""
    mcp, _prefix = await _make_server(lazy=False)
    resources = [*await mcp.list_resources(), *await mcp.list_resource_templates()]
    assert resources, "expected a non-empty resource surface"

    failures: dict[str, list[str]] = {}
    for resource in resources:
        uri = str(getattr(resource, "uri", None) or getattr(resource, "uri_template", None) or "?")
        record = get_resource_registration(resource)
        if record is None:
            failures[uri] = ["no registration record"]
        elif problems := record.validate():
            failures[uri] = problems
        elif record.size_hint not in SIZE_HINTS or record.default_detail not in DETAILS:
            failures[uri] = [f"bogus domain values {record.size_hint!r}/{record.default_detail!r}"]
    assert not failures, f"incomplete resource records: {failures}"


@pytest.mark.asyncio
async def test_every_get_endpoint_with_params_registers_a_resource() -> None:
    """Every parameterized GET endpoint registers a resource (issue #783).

    The expected set is derived from the **converted** fixture via
    ``derive_resource_uri`` — the same single source of truth the factory
    uses — so wildcard (``{filepath*}``) and query-suffix templates are
    represented correctly.  Filtering is off in this test config
    (``tool_filtering_enabled=False``), so the only exclusion is a
    ``deprecated`` operation.

    This covers "expected but not registered"; the reverse direction is
    covered by ``test_every_registered_resource_has_a_complete_record``.
    """
    mcp, _prefix = await _make_server(lazy=False)
    registered = await _resource_uris(mcp)

    spec = _converted_fixture()
    expected = {
        clean_resource_uri(derive_resource_uri(spec, path, "GET"))
        for path, item in spec["paths"].items()
        if "get" in item and "{" in path and not item["get"].get("deprecated", False)
    }

    assert expected, "expected at least one parameterized GET in the fixture"
    missing = expected - registered
    assert not missing, f"parameterized GET endpoints registered no resource: {sorted(missing)}"


@pytest.mark.asyncio
async def test_hyphenated_path_placeholders_carry_param_rename() -> None:
    """Every hyphenated path placeholder has an x-param-rename entry (#783).

    The resource and cache surfaces read this contract to bridge the wire
    spelling (``{repository-id}``) and the normalized kwarg
    (``repository_id``).  Pin the direction, not merely non-emptiness — a
    collision-derived map must not satisfy the assertion.
    """
    spec = _converted_fixture()
    checked = 0
    for path, item in spec["paths"].items():
        operation = item.get("get")
        if not isinstance(operation, dict):
            continue
        hyphenated = [name for name in _path_placeholders(path) if "-" in name]
        if not hyphenated:
            continue
        rename_map = cast("dict[str, str]", operation.get("x-param-rename") or {})
        for wire in hyphenated:
            normalized = wire.replace("-", "_")
            assert rename_map.get(normalized) == wire, (
                f"{path}: expected x-param-rename[{normalized!r}] == {wire!r}, got {rename_map!r}"
            )
            checked += 1
    assert checked, "expected at least one hyphenated path placeholder in the fixture"


def _path_placeholders(path: str) -> list[str]:
    """Path-placeholder names in a spec path (template form)."""
    from gitea_mcp_server.uri_utils import path_param_names

    return path_param_names(path)


@pytest.mark.asyncio
async def test_pinned_synthetic_surface_has_records() -> None:
    """The pinned synthetic surface matches exactly and every member has a record."""
    mcp, prefix = await _make_server(lazy=True)
    tools = await mcp.list_tools()
    synthetic = {tool.name for tool in tools if "synthetic" in (tool.tags or [])}

    assert synthetic == {f"{prefix}{name}" for name in PINNED_SYNTHETIC_TOOLS}

    failures = {tool.name: problems for tool in tools if (problems := _record_problems(tool))}
    assert not failures, f"incomplete synthetic records: {failures}"


@pytest.mark.asyncio
async def test_no_retired_registration_keys_on_exposed_components() -> None:
    """No ad-hoc flat registration key remains on any exposed component.

    Phase 2 invariant: registration metadata lives only under the sanctioned
    record key.  This is a denylist (FastMCP owns/futures other ``meta`` keys),
    not a positive whitelist of ``meta``.
    """
    mcp, _prefix = await _make_server(lazy=False)
    tools = list(await mcp.list_tools())
    resources = [*await mcp.list_resources(), *await mcp.list_resource_templates()]

    offenders: dict[str, list[str]] = {}
    for tool in tools:
        leaked = sorted(RETIRED_TOOL_META_KEYS.intersection(tool.meta or {}))
        if leaked:
            offenders[tool.name] = leaked
    for resource in resources:
        leaked = sorted(RETIRED_RESOURCE_META_KEYS.intersection(resource.meta or {}))
        if leaked:
            uri = str(
                getattr(resource, "uri", None) or getattr(resource, "uri_template", None) or "?"
            )
            offenders[uri] = leaked
    assert not offenders, f"retired registration keys present: {offenders}"


@pytest.mark.asyncio
async def test_get_tool_path_finalises_record() -> None:
    """The get_tool access path (post-search) also finalises the record.

    ``list_tools`` is only one of the two exposure seams; an agent that finds a
    tool via ``search_tools`` fetches it with ``get_tool`` before calling.
    """
    mcp, prefix = await _make_server(lazy=True)
    tool = await mcp.get_tool(f"{prefix}tool_info")
    assert tool is not None
    record = get_tool_registration(tool)
    assert record is not None
    assert record.validate() == []


@pytest.mark.asyncio
async def test_lazy_off_synthetic_subset_present() -> None:
    """The non-search synthetic tools are present with records regardless of lazy mode."""
    mcp, prefix = await _make_server(lazy=False)
    tools = await mcp.list_tools()
    synthetic = {tool.name for tool in tools if "synthetic" in (tool.tags or [])}

    assert synthetic == {f"{prefix}{name}" for name in _SYNTHETIC_WHEN_LAZY_OFF}
