"""Integration coverage for the synthetic/autogen contract unification.

Regression coverage for issue #691's acceptance criteria: synthetic tools
ride the same server-level contract transform as autogenerated tools, so
direct and proxied (``call_tool``) calls behave identically — virtual
params from the registry, pagination metadata, friendly validation errors,
and the format/detail rendering surface.
"""

import pytest
import respx
from fastmcp.exceptions import ToolError

from gitea_mcp_server.client import GiteaClient
from gitea_mcp_server.server import create_mcp_server
from tests.conftest import SimpleConfig
from tests.helpers.mcp_results import assert_dual_channel, get_structured


def _make_spec() -> dict:
    """Minimal Swagger spec with a couple of endpoints for search coverage."""
    return {
        "swagger": "2.0",
        "info": {"title": "Gitea API", "version": "1.0"},
        "paths": {
            "/repos/{owner}/{repo}/issues": {
                "get": {
                    "operationId": "issueListIssues",
                    "summary": "List issues in a repository",
                    "responses": {"200": {"description": "Success"}},
                }
            },
            "/repos/{owner}/{repo}/pulls": {
                "get": {
                    "operationId": "repoListPullRequests",
                    "summary": "List pull requests",
                    "responses": {"200": {"description": "Success"}},
                }
            },
        },
        "definitions": {},
    }


async def _make_server() -> tuple:
    """Build a full server and return (mcp, prefix)."""
    config = SimpleConfig(
        url="https://git.example.com",
        token="test_token",
        log_level="ERROR",
        tool_filtering_enabled=False,
        enable_lazy_loading=True,
    )
    gitea_client = GiteaClient(config)
    try:
        with respx.mock() as mock_http:
            mock_http.get("https://git.example.com/swagger.v1.json").respond(200, json=_make_spec())
            mcp = await create_mcp_server(gitea_client)
        return mcp, (config.tool_prefix or "")
    finally:
        await gitea_client.close()


class TestDirectVsProxiedParity:
    """Direct and proxied synthetic calls hit the same contract transform."""

    @pytest.mark.asyncio
    async def test_search_tools_direct_and_proxied_identical(self) -> None:
        """call_tool("gitea_search_tools") matches a direct call field-for-field."""
        mcp, prefix = await _make_server()

        args = {"query": "issue", "format": "json", "page": 1, "limit": 5}

        direct = get_structured(await mcp.call_tool(f"{prefix}search_tools", args))
        proxied = get_structured(
            await mcp.call_tool(
                f"{prefix}call_tool",
                {"name": f"{prefix}search_tools", "arguments": args},
            )
        )

        assert direct == proxied, "proxied call must match the direct call"
        names = {t["name"] for t in direct["result"]}
        assert f"{prefix}issue_list_issues" in names
        # Pagination metadata is present in structured_content (shared contract).
        assert "has_more" in direct
        assert "next_offset" in direct
        assert "total_count" in direct

    @pytest.mark.asyncio
    async def test_pagination_metadata_and_fetch_all(self) -> None:
        """page/limit slice and fetch_all both flow through the transform."""
        mcp, prefix = await _make_server()

        page = get_structured(
            await mcp.call_tool(
                f"{prefix}search_tools",
                {"query": "issue", "format": "json", "page": 1, "limit": 1},
            )
        )
        total = page["total_count"]
        assert total >= 1
        assert len(page["result"]) == 1
        assert page["has_more"] == (total > 1)

        all_pages = get_structured(
            await mcp.call_tool(
                f"{prefix}search_tools",
                {"query": "issue", "format": "json", "fetch_all": True},
            )
        )
        assert all_pages["total_count"] == total
        assert len(all_pages["result"]) == total
        assert all_pages["has_more"] is False

    @pytest.mark.asyncio
    async def test_format_markdown_renders_content(self) -> None:
        """format=markdown renders content; structured content carries data."""
        mcp, prefix = await _make_server()

        result = await mcp.call_tool(
            f"{prefix}search_tools",
            {"query": "issue", "format": "markdown"},
        )
        text = next(c.text for c in result.content if c.type == "text")
        assert f"{prefix}issue_list_issues" in text


class TestSyntheticValidationSurface:
    """Synthetic tools reject bad input with the friendly shared surface."""

    @pytest.mark.asyncio
    async def test_unknown_param_rejected_direct_and_proxied(self) -> None:
        """run_validation rejects typos instead of silently dropping them."""
        mcp, prefix = await _make_server()

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(f"{prefix}search_tools", {"query": "issue", "typo": 1})
        assert "Unknown parameter" in str(exc.value)

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(
                f"{prefix}call_tool",
                {
                    "name": f"{prefix}search_tools",
                    "arguments": {"query": "issue", "typo": 1},
                },
            )
        assert "Unknown parameter" in str(exc.value)

    @pytest.mark.asyncio
    async def test_pagination_bounds_friendly_error(self) -> None:
        """page=0 and limit beyond the bound are rejected with friendly messages."""
        mcp, prefix = await _make_server()

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(f"{prefix}search_tools", {"query": "issue", "page": 0})
        assert "page must be >= 1" in str(exc.value)
        assert "pydantic" not in str(exc.value).lower()

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(f"{prefix}search_tools", {"query": "issue", "limit": 101})
        assert "limit must be <= 100" in str(exc.value)

    @pytest.mark.asyncio
    async def test_declared_off_allowlist_param_reaches_impl(self) -> None:
        """tool_info's detail (declared, not allowlisted) still flows through.

        ``detail`` is a registry virtual-param name, but tool_info's allowlist
        is ``{"format"}``.  The impl declares ``detail``, so it must survive
        extraction (stay in kwargs, pass validation, reach the impl) —
        driving output_schema inclusion instead of being dropped.
        """
        mcp, prefix = await _make_server()

        result = get_structured(
            await mcp.call_tool(
                f"{prefix}tool_info",
                {"name": f"{prefix}search_tools", "format": "json", "detail": "full"},
            )
        )
        assert "output_schema" in result["result"]


class TestReadDocContract:
    """read_doc rides the transform with its format-only profile + limit_max."""

    @pytest.mark.asyncio
    async def test_read_doc_paginated_and_bound(self) -> None:
        """read_doc paginates guide lines; its limit_max=200 is enforced."""
        mcp, prefix = await _make_server()

        result = get_structured(
            await mcp.call_tool(f"{prefix}read_doc", {"topic": "labels", "limit": 50})
        )
        assert "content" in result["result"]
        assert "has_more" in result
        assert "total_count" in result

        # limit=200 is within read_doc's documented bound.
        await mcp.call_tool(f"{prefix}read_doc", {"topic": "labels", "limit": 200})

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(f"{prefix}read_doc", {"topic": "labels", "limit": 201})
        assert "limit must be <= 200" in str(exc.value)

    @pytest.mark.asyncio
    async def test_off_profile_virtual_params_rejected(self) -> None:
        """read_doc (format-only allowlist) rejects detail/fetch_all as unknown.

        Off-allowlist registry virtual params must not be silently dropped —
        they stay in kwargs and hit the shared unknown-parameter validation.
        """
        mcp, prefix = await _make_server()

        for bad_arg in ({"detail": "concise"}, {"fetch_all": True}):
            with pytest.raises(ToolError) as exc:
                await mcp.call_tool(f"{prefix}read_doc", {"topic": "labels", **bad_arg})
            param = next(iter(bad_arg))
            assert f"Unknown parameter(s): '{param}'" in str(exc.value)


class TestDualChannelContract:
    """The dual-channel contract holds on real call_tool results (issue #718).

    ``content`` is the guaranteed channel; ``structured_content`` is an
    optional mirror that duplicates it.  Asserted at the protocol level on
    actual tool calls, not only on unit-level ``ToolResult`` construction.
    """

    @pytest.mark.asyncio
    async def test_markdown_dual_channel(self) -> None:
        """format=markdown: content present, structured carries result + envelope."""
        mcp, prefix = await _make_server()

        result = await mcp.call_tool(
            f"{prefix}search_tools",
            {"query": "issue", "format": "markdown"},
        )
        sc = assert_dual_channel(result, fmt="markdown")
        assert "has_more" in sc
        assert "total_count" in sc

    @pytest.mark.asyncio
    async def test_json_envelope_in_text(self) -> None:
        """format=json: the envelope must be in the text beside result."""
        mcp, prefix = await _make_server()

        result = await mcp.call_tool(
            f"{prefix}search_tools",
            {"query": "issue", "format": "json", "page": 1, "limit": 5},
        )
        assert_dual_channel(result, fmt="json")


class TestMessageSchemaDeclaration:
    """The message key is declared only on tools that emit it (issue #718).

    Schema and runtime must never disagree: every tool that emits ``message``
    via ``empty_paginated_result`` declares it (nullable) in its output
    schema, and tools that never emit it (``read_doc``) do not.
    """

    _EMITTING = (
        "search",
        "search_tools",
        "search_resources",
        "search_docs",
        "list_resources",
        "list_hidden_tools",
    )

    @pytest.mark.asyncio
    async def test_message_declared_on_emitting_tools(self) -> None:
        """The emitting tools declare message (nullable) in output_schema."""
        mcp, prefix = await _make_server()
        tools = await mcp.list_tools()
        by_name = {t.name: t for t in tools}

        for name in self._EMITTING:
            tool = by_name[f"{prefix}{name}"]
            assert tool.output_schema is not None
            props = tool.output_schema["properties"]
            assert "message" in props, f"{name} must declare message"
            assert props["message"]["anyOf"] == [{"type": "string"}, {"type": "null"}]

    @pytest.mark.asyncio
    async def test_message_not_declared_on_read_doc(self) -> None:
        """read_doc never emits message, so its schema must not declare it."""
        mcp, prefix = await _make_server()
        tools = await mcp.list_tools()
        by_name = {t.name: t for t in tools}

        tool = by_name[f"{prefix}read_doc"]
        assert tool.output_schema is not None
        assert "message" not in tool.output_schema["properties"]


class TestListHiddenToolsContract:
    """list_hidden_tools rides the shared paginated-list contract.

    Exercises the registered wrapper (not just the impl) through the server,
    verifying the envelope shape and the reason filter surface.
    """

    @pytest.mark.asyncio
    async def test_list_hidden_tools_returns_envelope(self) -> None:
        """Calling the registered tool returns a well-formed paginated envelope."""
        mcp, prefix = await _make_server()

        result = get_structured(
            await mcp.call_tool(
                f"{prefix}list_hidden_tools",
                {"format": "json", "page": 1, "limit": 10},
            )
        )
        # Envelope keys are always present, even for an empty hidden-tool set.
        assert "result" in result
        assert "has_more" in result
        assert "next_offset" in result
        assert "total_count" in result
        assert isinstance(result["result"], list)

    @pytest.mark.asyncio
    async def test_list_hidden_tools_rejects_invalid_reason(self) -> None:
        """An invalid reason is rejected with a friendly message."""
        mcp, prefix = await _make_server()

        with pytest.raises(ToolError) as exc:
            await mcp.call_tool(
                f"{prefix}list_hidden_tools",
                {"reason": "bogus"},
            )
        assert "Invalid reason" in str(exc.value)
        assert "scope, excluded, deprecated" in str(exc.value)
