"""Generic agent-facing contract transform spine.

Autogenerated (OpenAPI provider) and synthetic tools both expose the same
agent-facing contract: virtual-parameter injection/extraction, argument
validation, friendly errors, and post-hoc formatting.  The execution
*backend* differs (route-aware HTTP vs. a local in-memory implementation),
so the per-call spine is factored into one generic builder parameterized by
an executor.

The spine produced by :func:`build_transform_fn` is the single code path
for both tool families:

    1. ``extract_from(kwargs, only=...)`` — pop virtual params (format,
       detail, fetch_all, sudo, content_type, ...).  Both tool families
       carry a per-tool allowlist in ``tool.meta["_virtual_params"]``
       (synthetic tools stamp it at registration; autogen tools have it
       stamped with the actually-injected set), so only injected params are
       popped — an off-profile registry-name key (e.g. ``fetch_all`` on an
       autogen tool) stays in kwargs and is rejected as unknown rather than
       silently dropped.
    2. ``validate_extracted(...)`` — validate each popped value against its
       registry schema (enum) **before** the executor, so an invalid
       ``format``/``detail``/``content_type`` never reaches the API (and a
       write never runs before the error).  The registry schema is the single
       source for injection and validation.
    3. ``apply_pre_hooks(...)`` — run pre-hooks (may mutate kwargs, e.g.
       content_type base64-encodes ``content``).
    4. Resolve the MCP ``Context`` via
       :func:`~gitea_mcp_server.context_utils.resolve_current_context` —
       progress reporting and structured logging degrade to no-ops when no
       session is active.
    5. ``executor(kwargs, extracted, ctx)`` — backend-specific execution.
       Executors return raw data only — an
       :class:`~gitea_mcp_server.tools.result_pipeline.ExecutionResult`
       (data, total_count, result shape).  The single result pipeline
       (:func:`~gitea_mcp_server.tools.result_pipeline.render`) then applies
       shape → paginate → format → ``ToolResult``.
    6. Attach ``_raw_schema``, ``response_type``, and ``view_hints`` (all read
       from ``tool.meta``) so the pipeline can render schema-aware output
       (``detail=concise``), dispatch a type-bound domain markdown formatter,
       and refine the generic schema-anchored view with the curated
       display-view deficiencies, and derive the formatter context (``extra``)
       from the call's path/query args so the formatter sees repo/type context.
    7. ``apply_to(result, extracted)`` — run post-hooks (sudo cleanup).

The executor contract is deliberately narrow: ``(kwargs, extracted, ctx) →
ExecutionResult`` with the ``Tool`` bound by closure at wrap time.  Autogen
tools pass the OpenAPI HTTP pipeline
(``_ToolWrappingTransform`` in ``server_setup/mcp_builder.py``); synthetic
tools pass their local implementation (see ``tools/synthetic_contract.py``).
API-specific concerns (route-aware HTTP execution, error translation,
response-class wrapping) stay inside the executor — never in this module.

``ToolResult`` is imported at runtime (not under ``TYPE_CHECKING``) because
the ``transform_fn`` return annotation is a string under ``from __future__
import annotations``: FastMCP's ``ParsedFunction`` resolves the function's
annotations via ``get_type_hints`` when building the tool schema, and
pydantic evaluates the string return annotation when building the input
``TypeAdapter``.  Without the runtime import, tool registration fails with
``NameError``.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any

from fastmcp.tools.base import ToolResult  # noqa: TC002 - see module docstring

from gitea_mcp_server.constants import DEFAULT_DETAIL, DEFAULT_PAGE_SIZE
from gitea_mcp_server.context_utils import resolve_current_context
from gitea_mcp_server.exceptions import ValidationError
from gitea_mcp_server.tools.result_pipeline import ExecutionResult, render
from gitea_mcp_server.tools.virtual_params import (
    apply_pre_hooks,
    apply_to,
    extract_from,
    validate_extracted,
)

if TYPE_CHECKING:
    from fastmcp.tools.base import Tool

    from gitea_mcp_server.openapi_types import OpenAPISpec

Executor = Callable[
    [dict[str, Any], dict[str, Any] | None, Any | None],
    Awaitable[ExecutionResult],
]
"""Backend-specific execution callable: ``(kwargs, extracted, ctx) → result``.

- ``kwargs`` — the tool arguments with virtual params already popped.
- ``extracted`` — the extracted virtual-param values (``format``,
  ``detail``, ``fetch_all``, ...) from :func:`extract_from`.
- ``ctx`` — the resolved MCP ``Context``, or ``None`` when no session is
  active (progress reporting and logging degrade gracefully).

Returns raw data as an :class:`~gitea_mcp_server.tools.result_pipeline.ExecutionResult`
(rendered by the single result pipeline in the spine).

The ``Tool`` being executed is bound by closure at wrap time — the executor
does not need to receive it.
"""

# Call-arg names forwarded to the display pipeline as formatter ``extra``:
# the context keys the domain formatters understand — repo
# scope (``owner``/``repo``, used by the labels views), org scope (``org``,
# the owner-equivalent on org-scoped label tools, #766), and the issue-list
# ``type`` filter (used by the issues title).  This is display *input*
# derived from the call, not display logic — the same category as the
# page/limit capture below.  ``call_markdown_formatter`` forwards ``extra``
# only to formatters that declare it, so carrying these keys is harmless
# for every other tool (synthetic tools never declare ``extra``).
_DISPLAY_CONTEXT_KEYS: tuple[str, ...] = ("owner", "repo", "org", "type")


def _derive_display_extra(kwargs: dict[str, Any]) -> dict[str, Any] | None:
    """Extract formatter context from the tool call's path/query args.

    Returns ``None`` when no context keys are present (the formatter then
    falls back to its graceful defaults, e.g. ``"?"`` headings).
    """
    extra = {k: kwargs[k] for k in _DISPLAY_CONTEXT_KEYS if kwargs.get(k) is not None}
    return extra or None


def build_transform_fn(
    tool: Tool,
    executor: Executor,
    *,
    openapi_spec: OpenAPISpec | None = None,
    default_format: str,
) -> Callable[..., Any]:
    """Build the per-call :func:`transform_fn` closure for a tool.

    The returned callable receives ``**kwargs`` (the agent's arguments) and
    runs the full agent-facing contract spine: extract virtual params, run
    pre-hooks, resolve the context, delegate to *executor*, render the raw
    ``ExecutionResult`` through the single result pipeline, then hand off
    to :func:`apply_to` for post-hooks (sudo cleanup).

    ``openapi_spec`` is captured by the closure and forwarded to
    :func:`render` — it enables root-list item summaries under
    ``detail="concise"`` (#759).  It is display metadata, deliberately *not*
    stored in ``tool.meta`` (meta is serialized with the tool; the full spec
    would bloat every ``list_tools`` response).

    ``default_format`` is the live server default (``Config.response_format``),
    captured by the closure.  It is required — not defaulted to a literal —
    so the configured value is the single source of the ``format`` default:
    the same value is injected into every tool schema by
    ``_ToolWrappingTransform`` and used here as the spine's fallback when the
    extracted ``format`` is absent.  ``detail`` is static and comes from
    :data:`~gitea_mcp_server.constants.DEFAULT_DETAIL`.

    Args:
        tool: The ``Tool`` being wrapped.  ``tool.meta["output_schema_raw"]``
            is attached to the extracted dict as ``_raw_schema`` so the
            pipeline can render schema-aware output.
            ``tool.meta["_virtual_params"]`` is the per-tool extraction
            allowlist for both families — only those registry virtual
            params are popped from kwargs; off-allowlist registry-name keys
            remain in kwargs for validation to reject as unknown.
        executor: Backend-specific execution callable (see :data:`Executor`).
            Autogen tools pass the HTTP pipeline; synthetic tools pass their
            local implementation.
        openapi_spec: Post-conversion OpenAPI 3.1 spec (or ``None``), captured
            by the closure and forwarded to :func:`render` so
            ``detail="concise"`` can summarize root-list items (#759).
        default_format: The live configured default response format
            (``Config.response_format``) — the single source of the
            ``format`` default.

    Returns:
        The ``transform_fn`` callable to attach via
        ``Tool.from_tool(tool, transform_fn=...)`` (or an equivalent
        wrapping path).
    """

    async def transform_fn(**kwargs: Any) -> ToolResult:
        # Pop virtual params (format, detail, sudo, fetch_all, content_type,
        # etc.).  Both tool families carry a per-tool allowlist
        # (tool.meta["_virtual_params"]): only allowlisted params are popped,
        # so an off-profile registry-name key (e.g. ``fetch_all`` on an
        # autogen tool, or on a format-only synthetic tool) stays in kwargs
        # and is rejected as unknown by validation instead of being silently
        # dropped.
        virtual_values = extract_from(
            kwargs,
            only=(tool.meta or {}).get("_virtual_params"),
        )

        # Validate the popped values against their registry schemas (enum)
        # *before* the executor: an invalid format/detail/content_type must be
        # rejected here, not after the HTTP call (and never after a write has
        # already run).  The registry schema is the single source for both
        # injection and validation.  ValidationError is the validation layer's
        # type; the agent-facing surface is a plain ValueError, matching the
        # executors' boundary convention.
        try:
            validate_extracted(virtual_values)
        except ValidationError as e:
            raise ValueError(str(e)) from e

        # Run pre-hooks.  Hooks may mutate kwargs (e.g. content_type
        # base64-encodes ``content``).
        apply_pre_hooks(virtual_values, kwargs)

        # Resolve the current MCP Context so progress reporting and
        # structured logging work inside the pipeline.
        ctx = await resolve_current_context()

        # Capture pagination state before the executor runs — page/limit are
        # real tool parameters (API query params for autogen, impl params for
        # synthetic), not virtual params, so they stay in kwargs.
        page = kwargs.get("page", 1)
        limit = kwargs.get("limit", DEFAULT_PAGE_SIZE)

        # Same for formatter context: owner/repo/type are real call args on
        # the tools whose domain formatters use them.
        display_extra = _derive_display_extra(kwargs)

        result = await executor(kwargs, virtual_values, ctx)

        # Attach raw_schema to the extracted dict so the pipeline can render
        # schema-aware output (detail=concise).  Not a VirtualParam —
        # pipeline metadata carried through the same channel as detail,
        # format, etc.
        virtual_values["_raw_schema"] = (tool.meta or {}).get("output_schema_raw")

        # Display type-binding key: the pre-wrap response type the
        # registration layer stored in tool.meta (same channel as
        # ``output_schema_raw``).  The pipeline maps it to a domain markdown
        # formatter; absent means the generic renderer.
        response_type = (tool.meta or {}).get("response_type")

        # Curated display-view deficiencies for the response type, resolved at
        # registration and carried in tool.meta — the render path consumes them
        # as data and never scans or mutates the spec (#775).
        view_hints = (tool.meta or {}).get("view_hints")

        # Executors return raw data; the single result pipeline renders it.
        # Run post-hooks on the rendered ToolResult and return.
        return apply_to(
            render(
                result,
                fmt=virtual_values.get("format", default_format),
                detail=virtual_values.get("detail", DEFAULT_DETAIL),
                page=page,
                limit=limit,
                fetch_all=virtual_values.get("fetch_all", False),
                schema=virtual_values.get("_raw_schema"),
                extra=display_extra,
                response_type=response_type,
                view_hints=view_hints,
                openapi_spec=openapi_spec,
            ),
            virtual_values,
        )

    return transform_fn


__all__ = [
    "Executor",
    "build_transform_fn",
]
