"""Generic agent-facing contract transform spine.

Autogenerated (OpenAPI provider) and synthetic tools both expose the same
agent-facing contract: virtual-parameter injection/extraction, argument
validation, friendly errors, and post-hoc formatting.  The execution
*backend* differs (route-aware HTTP vs. a local in-memory implementation),
so the per-call spine is factored into one generic builder parameterized by
an executor.

The spine produced by :func:`build_transform_fn` is the single code path
for both tool families:

    1. ``extract_from(kwargs, only=...)`` — pop virtual params (format,
       detail, fetch_all, sudo, content_type, ...).  Both tool families
       carry a per-tool allowlist in ``tool.meta["_virtual_params"]``
       (synthetic tools stamp it at registration; autogen tools have it
       stamped with the actually-injected set), so only injected params are
       popped — an off-profile registry-name key (e.g. ``fetch_all`` on an
       autogen tool) stays in kwargs and is rejected as unknown rather than
       silently dropped.
    2. ``apply_pre_hooks(...)`` — run pre-hooks (may mutate kwargs, e.g.
       content_type base64-encodes ``content``).
    3. Resolve the MCP ``Context`` via
       :func:`~gitea_mcp_server.context_utils.resolve_current_context` —
       progress reporting and structured logging degrade to no-ops when no
       session is active.
    4. ``executor(kwargs, extracted, ctx)`` — backend-specific execution.
       Executors return raw data only — an
       :class:`~gitea_mcp_server.tools.result_pipeline.ExecutionResult`
       (data, total_count, result shape).  The single result pipeline
       (:func:`~gitea_mcp_server.tools.result_pipeline.render`) then applies
       shape → paginate → format → ``ToolResult``.
    5. Attach ``_raw_schema`` to the extracted dict so the pipeline can
       render schema-aware output (``detail=concise``).
    6. ``apply_to(result, extracted)`` — run post-hooks (sudo cleanup).

The executor contract is deliberately narrow: ``(kwargs, extracted, ctx) →
ExecutionResult`` with the ``Tool`` bound by closure at wrap time.  Autogen
tools pass the OpenAPI HTTP pipeline
(``_ToolWrappingTransform`` in ``server_setup/mcp_builder.py``); synthetic
tools pass their local implementation (see ``tools/synthetic_contract.py``).
API-specific concerns (route-aware HTTP execution, error translation,
response-class wrapping) stay inside the executor — never in this module.

``ToolResult`` is imported at runtime (not under ``TYPE_CHECKING``) because
the ``transform_fn`` return annotation is a string under ``from __future__
import annotations``: FastMCP's ``ParsedFunction`` resolves the function's
annotations via ``get_type_hints`` when building the tool schema, and
pydantic evaluates the string return annotation when building the input
``TypeAdapter``.  Without the runtime import, tool registration fails with
``NameError``.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import TYPE_CHECKING, Any

from fastmcp.tools.base import ToolResult  # noqa: TC002 - see module docstring

from gitea_mcp_server.constants import DEFAULT_PAGE_SIZE
from gitea_mcp_server.context_utils import resolve_current_context
from gitea_mcp_server.tools.result_pipeline import ExecutionResult, render
from gitea_mcp_server.tools.virtual_params import apply_pre_hooks, apply_to, extract_from

if TYPE_CHECKING:
    from fastmcp.tools.base import Tool

Executor = Callable[
    [dict[str, Any], dict[str, Any] | None, Any | None],
    Awaitable[ExecutionResult],
]
"""Backend-specific execution callable: ``(kwargs, extracted, ctx) → result``.

- ``kwargs`` — the tool arguments with virtual params already popped.
- ``extracted`` — the extracted virtual-param values (``format``,
  ``detail``, ``fetch_all``, ...) from :func:`extract_from`.
- ``ctx`` — the resolved MCP ``Context``, or ``None`` when no session is
  active (progress reporting and logging degrade gracefully).

Returns raw data as an :class:`~gitea_mcp_server.tools.result_pipeline.ExecutionResult`
(rendered by the single result pipeline in the spine).

The ``Tool`` being executed is bound by closure at wrap time — the executor
does not need to receive it.
"""


def build_transform_fn(
    tool: Tool,
    executor: Executor,
) -> Callable[..., Any]:
    """Build the per-call :func:`transform_fn` closure for a tool.

    The returned callable receives ``**kwargs`` (the agent's arguments) and
    runs the full agent-facing contract spine: extract virtual params, run
    pre-hooks, resolve the context, delegate to *executor*, render the raw
    ``ExecutionResult`` through the single result pipeline, then hand off
    to :func:`apply_to` for post-hooks (sudo cleanup).

    Args:
        tool: The ``Tool`` being wrapped.  ``tool.meta["output_schema_raw"]``
            is attached to the extracted dict as ``_raw_schema`` so the
            pipeline can render schema-aware output.
            ``tool.meta["_virtual_params"]`` is the per-tool extraction
            allowlist for both families — only those registry virtual
            params are popped from kwargs; off-allowlist registry-name keys
            remain in kwargs for validation to reject as unknown.
        executor: Backend-specific execution callable (see :data:`Executor`).
            Autogen tools pass the HTTP pipeline; synthetic tools pass their
            local implementation.

    Returns:
        The ``transform_fn`` callable to attach via
        ``Tool.from_tool(tool, transform_fn=...)`` (or an equivalent
        wrapping path).
    """

    async def transform_fn(**kwargs: Any) -> ToolResult:
        # Pop virtual params (format, detail, sudo, fetch_all, content_type,
        # etc.).  Both tool families carry a per-tool allowlist
        # (tool.meta["_virtual_params"]): only allowlisted params are popped,
        # so an off-profile registry-name key (e.g. ``fetch_all`` on an
        # autogen tool, or on a format-only synthetic tool) stays in kwargs
        # and is rejected as unknown by validation instead of being silently
        # dropped.
        virtual_values = extract_from(
            kwargs,
            only=(tool.meta or {}).get("_virtual_params"),
        )

        # Run pre-hooks.  Hooks may mutate kwargs (e.g. content_type
        # base64-encodes ``content``).
        apply_pre_hooks(virtual_values, kwargs)

        # Resolve the current MCP Context so progress reporting and
        # structured logging work inside the pipeline.
        ctx = await resolve_current_context()

        # Capture pagination state before the executor runs — page/limit are
        # real tool parameters (API query params for autogen, impl params for
        # synthetic), not virtual params, so they stay in kwargs.
        page = kwargs.get("page", 1)
        limit = kwargs.get("limit", DEFAULT_PAGE_SIZE)

        result = await executor(kwargs, virtual_values, ctx)

        # Attach raw_schema to the extracted dict so the pipeline can render
        # schema-aware output (detail=concise).  Not a VirtualParam —
        # pipeline metadata carried through the same channel as detail,
        # format, etc.
        virtual_values["_raw_schema"] = (tool.meta or {}).get("output_schema_raw")

        # Executors return raw data; the single result pipeline renders it.
        # Run post-hooks on the rendered ToolResult and return.
        return apply_to(
            render(
                result,
                fmt=virtual_values.get("format", "markdown"),
                detail=virtual_values.get("detail", "full"),
                page=page,
                limit=limit,
                fetch_all=virtual_values.get("fetch_all", False),
                schema=virtual_values.get("_raw_schema"),
            ),
            virtual_values,
        )

    return transform_fn


__all__ = [
    "Executor",
    "build_transform_fn",
]
