"""Shared agent-facing contract for manually registered synthetic tools.

Autogenerated tools receive validation and pagination behaviour from the
OpenAPI provider transform. Synthetic tools are registered on the root
server, so they need a small equivalent at registration time. This module
contains only backend-independent behaviour; API execution and HTTP error
handling remain OpenAPI-provider concerns.
"""

from __future__ import annotations

import copy
import inspect
from functools import wraps
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from collections.abc import Callable

from gitea_mcp_server.validation import validate_page_limit

PAGINATION_SCHEMA_PROPERTIES: dict[str, dict[str, Any]] = {
    "has_more": {
        "type": "boolean",
        "description": "Whether another page is available.",
    },
    "next_offset": {
        "anyOf": [{"type": "integer"}, {"type": "null"}],
        "description": "The next page number, or null when this is the last page.",
    },
    "total_count": {
        "anyOf": [{"type": "integer"}, {"type": "null"}],
        "description": "Total matching items when known.",
    },
}
"""The standard pagination metadata returned in ``structured_content``."""


def paginated_output_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """Return *schema* with the standard pagination envelope declared.

    Pagination metadata is placed beside ``result`` in the runtime
    ``structured_content`` envelope, matching autogenerated tool output.
    The input is copied so callers can safely reuse their base schema.
    """
    result = copy.deepcopy(schema)
    properties = result.setdefault("properties", {})
    for name, property_schema in PAGINATION_SCHEMA_PROPERTIES.items():
        properties.setdefault(name, copy.deepcopy(property_schema))
    return result


def register_synthetic_tool(
    mcp: Any,
    *,
    paginated: bool = False,
    **tool_options: Any,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    """Register a synthetic tool with shared validation and output metadata.

    The wrapped callable keeps its original signature for FastMCP schema
    generation. At runtime, paginated tools validate ``page`` and ``limit``
    before entering their implementation. This is intentionally a generic
    wrapper rather than reuse of the OpenAPI execution transform: synthetic
    tools have no route, HTTP method, or API re-execution function.
    """
    if paginated and "output_schema" in tool_options:
        tool_options["output_schema"] = paginated_output_schema(
            tool_options["output_schema"]
        )

    def decorator(function: Callable[..., Any]) -> Callable[..., Any]:
        signature = inspect.signature(function)

        @wraps(function)
        async def contract_wrapper(*args: Any, **kwargs: Any) -> Any:
            if paginated:
                bound = signature.bind_partial(*args, **kwargs)
                validate_page_limit(
                    bound.arguments.get("page"),
                    bound.arguments.get("limit"),
                )
            return await function(*args, **kwargs)

        registered = mcp.tool(**tool_options)(contract_wrapper)
        return cast("Callable[..., Any]", registered)

    return decorator


__all__ = [
    "PAGINATION_SCHEMA_PROPERTIES",
    "paginated_output_schema",
    "register_synthetic_tool",
]
