"""Shared agent-facing contract for manually registered synthetic tools.

Autogenerated tools receive validation and pagination behaviour from the
OpenAPI provider transform. Synthetic tools are registered on the root
server, so they need a small equivalent at registration time. This module
contains only backend-independent behaviour; API execution and HTTP error
handling remain OpenAPI-provider concerns.
"""

from __future__ import annotations

import copy
import inspect
from functools import wraps
from typing import TYPE_CHECKING, Annotated, Any, cast, get_args, get_origin

if TYPE_CHECKING:
    from collections.abc import Callable

from pydantic import Field

from gitea_mcp_server.constants import PAGE_SIZE_MAX
from gitea_mcp_server.pagination import PAGINATION_SCHEMA_PROPERTIES
from gitea_mcp_server.validation import validate_page_limit


def paginated_output_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """Return *schema* with the standard pagination envelope declared.

    Pagination metadata is placed beside ``result`` in the runtime
    ``structured_content`` envelope, matching autogenerated tool output.
    The input is copied so callers can safely reuse their base schema.
    """
    result = copy.deepcopy(schema)
    properties = result.setdefault("properties", {})
    for name, property_schema in PAGINATION_SCHEMA_PROPERTIES.items():
        properties.setdefault(name, copy.deepcopy(property_schema))
    return result


def _annotation_with_bounds(annotation: Any, extra: dict[str, Any]) -> Any:
    """Return *annotation* with schema-only *extra* bounds appended.

    Additive by contract: every existing metadata item survives.  Pydantic
    merges multiple ``FieldInfo`` items, so the bounds ``Field`` is appended
    rather than replacing the annotation.  String metadata (FastMCP's short
    description form, e.g. ``Annotated[int, "Page number (1-based, default 1)"]``)
    is promoted to ``Field(description=...)`` first — a bare string would
    otherwise be shadowed by the appended ``Field`` and its description lost.
    """
    if get_origin(annotation) is not Annotated:
        return Annotated[annotation, Field(json_schema_extra=dict(extra))]
    base, *metadata = get_args(annotation)
    promoted = [
        Field(description=item) if isinstance(item, str) else item
        for item in metadata
    ]
    return Annotated[base, *promoted, Field(json_schema_extra=dict(extra))]


def _annotations_with_pagination_bounds(
    annotations: dict[str, Any],
    limit_max: int,
) -> dict[str, Any]:
    """Return *annotations* with page/limit bounds declared, nothing dropped.

    Mirrors the additive schema augmentation autogen tools receive from
    ``validation.augment_schema_with_validation`` (inject ``minimum`` /
    ``maximum`` without replacing existing schema keys).  FastMCP builds the
    tool's parameter schema from the function annotations at registration
    time; declaring the bounds here makes them machine-readable in the
    schema, so ``tool_info`` and the ``gitea://tool/{name}/schema`` resource
    surface the per-tool page-size maximum to agents instead of a hardcoded
    doc number — matching autogen tools whose ``SCHEMA_CONSTRAINTS`` declare
    ``page.minimum`` / ``per_page.maximum``.

    The bounds are declared via ``Field(json_schema_extra=...)`` —
    schema-only, so pydantic does not enforce them at the MCP boundary.
    ``Field(ge=..., le=...)`` would reject invalid values with a pydantic
    ``ValidationError`` (leaking ``errors.pydantic.dev`` URLs to agents)
    before the wrapper's friendly ``validate_page_limit`` runs.  Schema-only
    declaration keeps the error surface identical to autogen tools: the
    wrapper rejects with ``"page must be >= 1"`` / ``"limit must be <= N"``.
    """
    result = dict(annotations)
    for param_name, extra in (
        ("page", {"minimum": 1}),
        ("limit", {"minimum": 1, "maximum": limit_max}),
    ):
        if param_name not in result:
            continue
        result[param_name] = _annotation_with_bounds(result[param_name], extra)
    return result


def register_synthetic_tool(
    mcp: Any,
    *,
    paginated: bool = False,
    limit_max: int | None = None,
    **tool_options: Any,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    """Register a synthetic tool with shared validation and output metadata.

    The wrapped callable keeps its original signature for FastMCP schema
    generation. At runtime, paginated tools validate ``page`` and ``limit``
    before entering their implementation. This is intentionally a generic
    wrapper rather than reuse of the OpenAPI execution transform: synthetic
    tools have no route, HTTP method, or API re-execution function.

    Args:
        mcp: The FastMCP server instance to register on.
        paginated: When True, validate ``page``/``limit`` at runtime and
            declare the pagination envelope in ``output_schema``.
        limit_max: Upper bound for ``limit``.  Defaults to ``PAGE_SIZE_MAX``
            (100); pass a custom value for tools whose documented maximum
            differs (e.g. ``read_doc`` paginates guide lines and allows 200).
            The bound is declared in the tool's parameter schema (as
            ``maximum``) so agents discover it via ``tool_info``.
    """
    if paginated and "output_schema" in tool_options:
        tool_options["output_schema"] = paginated_output_schema(
            tool_options["output_schema"]
        )

    effective_limit_max = limit_max if limit_max is not None else PAGE_SIZE_MAX

    def decorator(function: Callable[..., Any]) -> Callable[..., Any]:
        signature = inspect.signature(function)

        @wraps(function)
        async def contract_wrapper(*args: Any, **kwargs: Any) -> Any:
            if paginated:
                bound = signature.bind_partial(*args, **kwargs)
                validate_page_limit(
                    bound.arguments.get("page"),
                    bound.arguments.get("limit"),
                    limit_max=effective_limit_max,
                )
            return await function(*args, **kwargs)

        if paginated:
            # Declare page/limit bounds in the parameter schema so
            # ``tool_info`` surfaces them (agents discover per-tool maxima
            # instead of relying on hardcoded doc numbers).  Additive —
            # all existing annotation metadata is preserved, mirroring the
            # autogen path's ``augment_schema_with_validation``.
            contract_wrapper.__annotations__ = _annotations_with_pagination_bounds(
                contract_wrapper.__annotations__, effective_limit_max
            )

        return cast("Callable[..., Any]", mcp.tool(**tool_options)(contract_wrapper))

    return decorator


__all__ = [
    "PAGINATION_SCHEMA_PROPERTIES",
    "paginated_output_schema",
    "register_synthetic_tool",
]
