"""Shared agent-facing contract for manually registered synthetic tools.

Autogenerated tools receive validation and pagination behaviour from the
OpenAPI provider transform. Synthetic tools are registered on the root
server, so they need a small equivalent at registration time. This module
contains only backend-independent behaviour; API execution and HTTP error
handling remain OpenAPI-provider concerns.
"""

from __future__ import annotations

import copy
import inspect
from functools import wraps
from typing import TYPE_CHECKING, Annotated, Any, cast, get_args, get_origin

if TYPE_CHECKING:
    from collections.abc import Callable

from pydantic import Field
from pydantic.fields import FieldInfo

from gitea_mcp_server.constants import PAGE_SIZE_MAX
from gitea_mcp_server.pagination import PAGINATION_SCHEMA_PROPERTIES
from gitea_mcp_server.validation import validate_page_limit


def paginated_output_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """Return *schema* with the standard pagination envelope declared.

    Pagination metadata is placed beside ``result`` in the runtime
    ``structured_content`` envelope, matching autogenerated tool output.
    The input is copied so callers can safely reuse their base schema.
    """
    result = copy.deepcopy(schema)
    properties = result.setdefault("properties", {})
    for name, property_schema in PAGINATION_SCHEMA_PROPERTIES.items():
        properties.setdefault(name, copy.deepcopy(property_schema))
    return result


def _annotation_description(annotation: Any) -> str | None:
    """Extract the description from a parameter annotation, if any.

    Synthetic tools declare parameter descriptions either as an
    ``Annotated[int, "text"]`` string or as ``Annotated[int, Field(description=...)]``.
    Returns ``None`` when the annotation carries no description so callers can
    tell "no description" apart from an empty string.
    """
    if get_origin(annotation) is not Annotated:
        return None
    for metadata in get_args(annotation)[1:]:
        if isinstance(metadata, str) and metadata:
            return metadata
        if isinstance(metadata, FieldInfo) and metadata.description:
            return metadata.description
    return None


def _annotate_pagination_bounds(
    function: Callable[..., Any],
    limit_max: int,
) -> None:
    """Rewrite ``page``/``limit`` annotations with declared bounds.

    FastMCP builds the tool's parameter schema from the function signature
    at registration time.  Injecting ``Field(ge=1, le=limit_max)`` into the
    ``limit`` annotation (and ``Field(ge=1)`` into ``page``) makes the bounds
    machine-readable in the schema, so ``tool_info`` and the
    ``gitea://tool/{name}/schema`` resource surface them to agents — the
    per-tool page-size maximum becomes discoverable instead of a hardcoded
    number in prose, matching autogen tools whose ``SCHEMA_CONSTRAINTS``
    declare ``page.minimum`` / ``per_page.maximum``.

    Existing descriptions are preserved: the original annotation (string or
    ``FieldInfo``) is read via :func:`_annotation_description` and folded into
    the new ``Field``.  ``@wraps`` copies the original annotations onto the
    wrapper, so the rewrite targets the wrapper FastMCP inspects.  Runtime
    validation stays in ``register_synthetic_tool`` (it also guards direct
    invocation paths that bypass schema-driven validation).
    """
    annotations = dict(function.__annotations__)
    for param_name, bound in (("page", (1, None)), ("limit", (1, limit_max))):
        if param_name not in annotations:
            continue
        description = _annotation_description(annotations[param_name])
        if bound[1] is None:
            field = Field(ge=bound[0], description=description) if description else Field(ge=bound[0])
        else:
            field = (
                Field(ge=bound[0], le=bound[1], description=description)
                if description
                else Field(ge=bound[0], le=bound[1])
            )
        annotations[param_name] = Annotated[int, field]
    function.__annotations__ = annotations


def register_synthetic_tool(
    mcp: Any,
    *,
    paginated: bool = False,
    limit_max: int | None = None,
    **tool_options: Any,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    """Register a synthetic tool with shared validation and output metadata.

    The wrapped callable keeps its original signature for FastMCP schema
    generation. At runtime, paginated tools validate ``page`` and ``limit``
    before entering their implementation. This is intentionally a generic
    wrapper rather than reuse of the OpenAPI execution transform: synthetic
    tools have no route, HTTP method, or API re-execution function.

    Args:
        mcp: The FastMCP server instance to register on.
        paginated: When True, validate ``page``/``limit`` at runtime and
            declare the pagination envelope in ``output_schema``.
        limit_max: Upper bound for ``limit``.  Defaults to ``PAGE_SIZE_MAX``
            (100); pass a custom value for tools whose documented maximum
            differs (e.g. ``read_doc`` paginates guide lines and allows 200).
            The bound is declared in the tool's parameter schema (as
            ``maximum``) so agents discover it via ``tool_info``.
    """
    if paginated and "output_schema" in tool_options:
        tool_options["output_schema"] = paginated_output_schema(
            tool_options["output_schema"]
        )

    effective_limit_max = limit_max if limit_max is not None else PAGE_SIZE_MAX

    def decorator(function: Callable[..., Any]) -> Callable[..., Any]:
        signature = inspect.signature(function)

        @wraps(function)
        async def contract_wrapper(*args: Any, **kwargs: Any) -> Any:
            if paginated:
                bound = signature.bind_partial(*args, **kwargs)
                validate_page_limit(
                    bound.arguments.get("page"),
                    bound.arguments.get("limit"),
                    limit_max=effective_limit_max,
                )
            return await function(*args, **kwargs)

        if paginated:
            # Declare page/limit bounds in the parameter schema so
            # ``tool_info`` surfaces them (agents discover per-tool maxima
            # instead of relying on hardcoded doc numbers).
            _annotate_pagination_bounds(contract_wrapper, effective_limit_max)

        return cast("Callable[..., Any]", mcp.tool(**tool_options)(contract_wrapper))

    return decorator


__all__ = [
    "PAGINATION_SCHEMA_PROPERTIES",
    "paginated_output_schema",
    "register_synthetic_tool",
]
