"""Tests for resources/auto.py.

Covers:
    - register_auto_generated_resources registration behavior
    - _derive_resource_name conversion logic
    - Auto-generated resource docstrings
    - Factory routing for auto-generated resources
    - skip_uris exclusion
    - Error handling (404, structured errors)
"""

import json
from collections.abc import Callable
from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastmcp.exceptions import ResourceError
from mcp.server.fastmcp import FastMCP

from gitea_mcp_server.constants import HTTP_STATUS_NOT_FOUND
from gitea_mcp_server.exceptions import GiteaAPIError
from gitea_mcp_server.openapi_types import OpenAPISpec
from gitea_mcp_server.resources.auto import register_auto_generated_resources
from tests.helpers.spec_fixtures import make_openapi_spec


class TestRegisterAutoGeneratedResources:
    """Tests for register_auto_generated_resources."""

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        # Mock the resource decorator to track registrations
        mcp.resource = MagicMock(return_value=lambda func: func)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        """Create a mock GiteaClient."""
        return AsyncMock()

    @pytest.fixture
    def openapi_spec_with_get(self) -> OpenAPISpec:
        """OpenAPI spec with a simple GET endpoint.

        Uses realistic paths without a /gitea prefix -- matches the actual
        Gitea/Forgejo OpenAPI spec at /swagger.v1.json.
        The URI scheme is always gitea:// for consistent namespacing.
        """
        return make_openapi_spec(
            paths={
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repository information",
                        "description": "Get details about a repository",
                        "operationId": "getRepo",
                        "tags": ["repository"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List repository issues",
                        "operationId": "listRepoIssues",
                        "tags": ["repository", "issue"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "state",
                                "in": "query",
                                "required": False,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
            }
        )

    async def test_registers_one_resource_per_get_endpoint(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock, openapi_spec_with_get: OpenAPISpec
    ) -> None:
        """One mcp.resource() call per GET endpoint."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )
        assert mock_mcp.resource.call_count == 2

    async def test_registers_expected_uri_templates(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock, openapi_spec_with_get: OpenAPISpec
    ) -> None:
        """URI templates match the OpenAPI path structure."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )
        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in uri_templates
        assert "gitea://repos/{owner}/{repo}/issues" in uri_templates

    async def test_resource_function_has_docstring(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock, openapi_spec_with_get: OpenAPISpec
    ) -> None:
        """Test that auto-generated resources have proper docstrings."""
        # Track registered functions
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )

        # Find the resource for /repos/{owner}/{repo}
        repo_entry = next(r for r in registered if r[0] == "gitea://repos/{owner}/{repo}")
        resource_func = repo_entry[1]

        assert resource_func.__doc__ is not None
        assert "Get repository information" in resource_func.__doc__

    async def test_resources_have_meaningful_names(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock, openapi_spec_with_get: OpenAPISpec
    ) -> None:
        """Test that auto-generated resources get names from operationId."""
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, kwargs.get("name", func.__name__)))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )

        names = dict(registered)
        # operationId "getRepo" -> name "get_repo"
        assert names["gitea://repos/{owner}/{repo}"] == "get_repo"
        # operationId "listRepoIssues" -> name "list_repo_issues"
        assert names["gitea://repos/{owner}/{repo}/issues"] == "list_repo_issues"

    async def test_resources_have_required_scope_in_meta(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock, openapi_spec_with_get: OpenAPISpec
    ) -> None:
        """Test that auto-generated resources carry required_scope in meta passed to mcp.resource()."""
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, kwargs.get("meta", {})))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )

        metas = dict(registered)
        repo_meta = metas["gitea://repos/{owner}/{repo}"]
        issues_meta = metas["gitea://repos/{owner}/{repo}/issues"]
        assert repo_meta.get("required_scope") == "read:repository"
        # issues endpoint has tags ["repository", "issue"] -> set iteration order is non-deterministic
        assert issues_meta.get("required_scope") in (
            "read:issue",
            "read:repository",
        )

    async def test_ignores_non_get_methods(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Test that POST/PUT/DELETE endpoints are not registered."""
        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "post": {"summary": "Create repo", "operationId": "createRepo"},
                    "put": {"summary": "Update repo", "operationId": "updateRepo"},
                }
            }
        }
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec)

        # Should not register any resources (no GET)
        mock_mcp.resource.assert_not_called()

    async def test_handles_empty_spec(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Test that empty spec doesn't crash."""
        spec: OpenAPISpec = {"paths": {}}
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec)
        mock_mcp.resource.assert_not_called()


class TestDeriveResourceName:
    """Tests for _derive_resource_name helper."""

    def test_uses_operation_id_camel_case(self) -> None:
        """Test camelCase operationId is converted to snake_case."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": "getRepo"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "get_repo"

    def test_uses_operation_id_snake_case(self) -> None:
        """Test snake_case operationId is kept as-is."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": "issue_get_issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "issue_get_issue"

    def test_preserves_multi_word_snake_case(self) -> None:
        """Test multi-word snake_case is preserved."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": "org_list_members"}
        name = _derive_resource_name(operation, "/orgs/{org}/members")
        assert name == "org_list_members"

    def test_falls_back_to_path_when_no_operation_id(self) -> None:
        """Test fallback when operationId is missing."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"summary": "Get an issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        # Path segments sans path params: repos, issues
        assert name == "repos_issues"

    def test_handles_empty_operation_id(self) -> None:
        """Test fallback when operationId is empty string."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": ""}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "repos_issues"

    def test_handles_complex_camel_case(self) -> None:
        """Test complex camelCase with multiple words."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": "issueCreateIssueComment"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}/comments")
        assert name == "issue_create_issue_comment"

    def test_handles_leading_uppercase(self) -> None:
        """Test leading uppercase in camelCase like 'RepoGet'."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"operationId": "RepoGet"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "repo_get"

    def test_all_path_param_fallback(self) -> None:
        """When path has only param segments, use cleaned param names."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"summary": "Test"}
        name = _derive_resource_name(operation, "/{owner}/{repo}")
        # No static segments, fallback to stripped param names
        assert name == "owner_repo"

    def test_empty_path_returns_resource(self) -> None:
        """When all segments filtered out, fallback to 'resource'."""
        from gitea_mcp_server.resources.factory import _derive_resource_name

        operation = {"summary": "Test"}
        name = _derive_resource_name(operation, "/{param}")
        assert name == "param"


class TestAutoGeneratedResourceDocstring:
    """Tests for auto-generated resource docstrings."""

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        return MagicMock(spec=FastMCP)

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        return AsyncMock()

    async def test_docstring_fallback_to_derived_name(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """When operation has no summary or description, fall back to the derived name — never API plumbing."""
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "operationId": "getRepo",
                        # no summary, no description
                    }
                }
            }
        }

        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())

        assert len(registered) == 1
        _, resource_func = registered[0]
        doc = resource_func.__doc__
        assert doc is not None
        # The fallback is the derived snake_case name — not "Resource for GET {path}".
        assert doc == "get_repo"
        assert "GET" not in doc
        assert "/repos/{owner}/{repo}" not in doc

    async def test_docstring_includes_summary_and_description(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Docstring includes both summary and description when both present."""
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repo",
                        "description": "Detailed description of getting a repo",
                        "operationId": "getRepo",
                    }
                }
            }
        }

        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())

        func = registered[0][1]
        assert func.__doc__ is not None
        assert "Get repo" in func.__doc__
        assert "Detailed description" in func.__doc__


class TestAutoGeneratedResourceViaFactory:
    """Tests for auto-generated resources now routed through make_api_resource.

    Missing path parameter validation is handled by FastMCP's URI template
    routing at the framework level — the handler itself assumes all params
    are present.  These tests verify the factory path produces correct
    handlers.
    """

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        return MagicMock(spec=FastMCP)

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        client = AsyncMock()
        client.request = AsyncMock(return_value={"id": 1, "name": "repo"})
        return client

    async def test_handler_with_all_params(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Handler returns data when all required params are provided."""
        spec = make_openapi_spec(
            paths={
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repo",
                        "operationId": "getRepo",
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                }
            }
        )

        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())

        func = registered[0][1]
        result = await func(owner="myorg", repo="myrepo")
        assert result.contents[0].content is not None
        parsed = json.loads(result.contents[0].content)
        assert parsed == {"id": 1, "name": "repo"}

    async def test_passes_query_params(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Handler passes query params from the operation spec."""
        spec = make_openapi_spec(
            paths={
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List issues",
                        "operationId": "listIssues",
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "state",
                                "in": "query",
                                "required": False,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                }
            }
        )

        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())
        assert len(registered) >= 1


class TestRegisterAutoGeneratedSkipUri:
    """Tests for skip_uris in auto-generated resources."""

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        return MagicMock(spec=FastMCP)

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        return AsyncMock()

    async def test_skip_uris_excluded(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Resources with URIs in skip_uris are not registered."""
        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repo",
                        "operationId": "getRepo",
                    }
                }
            }
        }

        register_auto_generated_resources(
            mock_mcp,
            mock_gitea_client,
            spec,
            skip_uris={"gitea://repos/{owner}/{repo}"},
        )

        mock_mcp.resource.assert_not_called()

    async def test_skip_uris_excluded_with_query_suffix(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Resources are skipped even when skip_uris has {?query} suffix.

        Auto-generated resources build URIs without query suffixes
        (e.g. "gitea://repos/{owner}/{repo}/issues"), but custom
        resources register with {?state,type} suffixes.  The skip
        mechanism normalizes by stripping the suffix so the base
        URIs match.
        """
        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List issues",
                        "operationId": "listIssues",
                    }
                }
            }
        }

        register_auto_generated_resources(
            mock_mcp,
            mock_gitea_client,
            spec,
            skip_uris={"gitea://repos/{owner}/{repo}/issues{?state,type}"},
        )

        mock_mcp.resource.assert_not_called()

    async def test_value_error_during_registration_logged(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """ValueError from mcp.resource is caught and logged."""
        mock_mcp.resource = MagicMock(side_effect=ValueError("Duplicate URI"))

        spec: OpenAPISpec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repo",
                        "operationId": "getRepo",
                    }
                }
            }
        }

        # Should not raise - ValueError is caught
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())


class TestAutoGeneratedWildcardUri:
    """Auto resources render {param*} from the Rule C wildcard extension."""

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        return MagicMock(spec=FastMCP)

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        return AsyncMock()

    def _spec_with_contents(self) -> OpenAPISpec:
        """Spec with the contents endpoint carrying x-wildcard-path-param."""
        return make_openapi_spec(
            paths={
                "/repos/{owner}/{repo}/contents/{filepath}": {
                    "get": {
                        "summary": "Get file contents",
                        "operationId": "repoGetContents",
                        "x-wildcard-path-param": "filepath",
                    }
                }
            }
        )

    async def test_wildcard_extension_renders_param_star(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """The auto URI for a wildcard path uses {param*}."""
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append(uri)
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp,
            mock_gitea_client,
            self._spec_with_contents(),
            skip_uris=set(),
        )

        assert "gitea://repos/{owner}/{repo}/contents/{filepath*}" in registered

    async def test_skip_uris_matches_wildcard_uri(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """A custom wrapper's wildcard URI suppresses the auto resource.

        The wrapper derives the same template (via derive_resource_uri), so
        the skip fires on the exact wildcard URI.
        """
        register_auto_generated_resources(
            mock_mcp,
            mock_gitea_client,
            self._spec_with_contents(),
            skip_uris={"gitea://repos/{owner}/{repo}/contents/{filepath*}"},
        )

        mock_mcp.resource.assert_not_called()


class TestAutoGeneratedResourceErrors:
    """Tests for auto-generated resource error handling."""

    @pytest.fixture
    def mock_mcp(self) -> MagicMock:
        """Create a mock FastMCP instance."""
        return MagicMock(spec=FastMCP)

    @pytest.fixture
    def mock_gitea_client(self) -> AsyncMock:
        """Create a mock GiteaClient."""
        return AsyncMock()

    async def test_404_raises_structured_error(
        self, mock_mcp: MagicMock, mock_gitea_client: AsyncMock
    ) -> None:
        """Test auto-generated resource raises ResourceError with proper structure on 404."""
        spec = make_openapi_spec(
            paths={
                "/test/{id}": {
                    "get": {
                        "summary": "Test endpoint",
                        "operationId": "testEndpoint",
                        "parameters": [
                            {
                                "name": "id",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            }
                        ],
                    }
                }
            }
        )

        # Track registered functions
        registered = []

        def track_decorator(uri: str, **kwargs: Any) -> Callable:
            def decorator(func: Callable) -> Callable:
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())

        assert len(registered) == 1
        uri, resource_func = registered[0]
        assert uri == "gitea://test/{id}"

        # Simulate 404 error from the real production exception
        mock_gitea_client.request = AsyncMock(
            side_effect=GiteaAPIError("Not Found", status_code=HTTP_STATUS_NOT_FOUND),
        )

        with pytest.raises(ResourceError) as exc_info:
            await resource_func(id="123")

        error_data = exc_info.value.args[0]
        # Auto resources now use the factory's _request_and_wrap which formats
        # the error with the default "Resource not found." message.
        assert error_data["code"] == "NOT_FOUND"
        assert error_data["message"] == "Resource not found."
        assert error_data["resource_type"] == "api"
        assert error_data["resource_id"] == "/test/123"
