"""Tests for the resources module."""

import base64
import inspect
import json
from unittest.mock import AsyncMock, MagicMock, Mock

import pytest
from fastmcp.exceptions import ResourceError
from mcp.server.fastmcp import FastMCP

from gitea_mcp_server.constants import HTTP_STATUS_NOT_FOUND
from gitea_mcp_server.exceptions import GiteaAPIError
from gitea_mcp_server.resources.auto import register_auto_generated_resources
from gitea_mcp_server.resources.custom import (
    _find_matching_token_scopes,
    register_custom_resources,
)
from gitea_mcp_server.resources.format import (
    _build_server_info_markdown,
    _format_datetime,
    _format_issues_markdown,
    _format_pulls_markdown,
    _format_release_markdown,
    _format_repo_markdown,
    _format_user_markdown,
    _handle_not_found,
)
from gitea_mcp_server.resources.registry import ResourceRegistry


class TestFormatDateTime:
    """Tests for _format_datetime."""

    def test_formats_iso_datetime(self):
        """Test ISO datetime string is formatted correctly."""
        dt = "2024-01-15T10:30:00Z"
        result = _format_datetime(dt)
        assert result == "2024-01-15 10:30:00 UTC"

    def test_handles_none(self):
        """Test None returns N/A."""
        assert _format_datetime(None) == "N/A"

    def test_handles_empty_string(self):
        """Test empty string returns N/A."""
        assert _format_datetime("") == "N/A"

    def test_handles_invalid_format(self):
        """Test invalid format returns original string."""
        assert _format_datetime("not a date") == "not a date"


class TestFormatRepoMarkdown:
    """Tests for _format_repo_markdown."""

    def test_formats_repo_completely(self):
        """Test repository is formatted with all fields."""
        repo = {
            "full_name": "owner/repo",
            "description": "Test repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
            "default_branch": "main",
            "stargazers_count": 42,
            "forks_count": 10,
            "open_issues_count": 5,
            "size": 1024,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-15T00:00:00Z",
            "topics": ["test", "example"],
            "license": {"name": "MIT"},
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "**Description**: Test repo" in result
        assert "| Owner | owner |" in result
        assert "| Stars | 42 |" in result
        assert "**Topics**: test, example" in result
        assert "**License**: MIT" in result

    def test_handles_missing_fields(self):
        """Test repo with missing optional fields."""
        repo = {
            "full_name": "owner/repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "No description" in result
        assert "None" in result  # topics, license etc.


class TestRegisterAutoGeneratedResources:
    """Tests for register_auto_generated_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        # Mock the resource decorator to track registrations
        mcp.resource = MagicMock(return_value=lambda func: func)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    @pytest.fixture
    def openapi_spec_with_get(self):
        """OpenAPI spec with a simple GET endpoint.

        Uses realistic paths without a /gitea prefix -- matches the actual
        Gitea/Forgejo OpenAPI spec at /swagger.v1.json.
        The URI scheme is always gitea:// for consistent namespacing.
        """
        return {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repository information",
                        "description": "Get details about a repository",
                        "operationId": "getRepo",
                        "tags": ["repository"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List repository issues",
                        "operationId": "listRepoIssues",
                        "tags": ["repository", "issue"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "state",
                                "in": "query",
                                "required": False,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
            }
        }

    async def test_registers_one_resource_per_get_endpoint(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """One mcp.resource() call per GET endpoint."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )
        assert mock_mcp.resource.call_count == 2

    async def test_registers_expected_uri_templates(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """URI templates match the OpenAPI path structure."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )
        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in uri_templates
        assert "gitea://repos/{owner}/{repo}/issues" in uri_templates

    async def test_registry_records_each_endpoint(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Each endpoint is recorded in the registry with its URI."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )
        assert mock_registry.record.call_count == 2
        recorded_uris = [call[1]["uri"] for call in mock_registry.record.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in recorded_uris
        assert "gitea://repos/{owner}/{repo}/issues" in recorded_uris

    async def test_resource_function_has_docstring(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources have proper docstrings."""
        # Track registered functions
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        # Find the resource for /repos/{owner}/{repo}
        repo_entry = next(r for r in registered if r[0] == "gitea://repos/{owner}/{repo}")
        resource_func = repo_entry[1]

        assert resource_func.__doc__ is not None
        assert "Get repository information" in resource_func.__doc__

    async def test_resources_have_meaningful_names(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources get names from operationId."""
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, kwargs.get("name", func.__name__)))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        names = {uri: name for uri, name in registered}
        # operationId "getRepo" -> name "get_repo"
        assert names["gitea://repos/{owner}/{repo}"] == "get_repo"
        # operationId "listRepoIssues" -> name "list_repo_issues"
        assert names["gitea://repos/{owner}/{repo}/issues"] == "list_repo_issues"

    async def test_resources_have_required_scope_in_meta(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources carry required_scope in meta passed to mcp.resource()."""
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, kwargs.get("meta", {})))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        metas = {uri: meta for uri, meta in registered}
        repo_meta = metas["gitea://repos/{owner}/{repo}"]
        issues_meta = metas["gitea://repos/{owner}/{repo}/issues"]
        assert repo_meta.get("fastmcp", {}).get("_internal", {}).get("required_scope") == "read:repository"
        # issues endpoint has tags ["repository", "issue"] -> set iteration order is non-deterministic
        assert issues_meta.get("fastmcp", {}).get("_internal", {}).get("required_scope") in (
            "read:issue",
            "read:repository",
        )

    async def test_resources_record_required_scope_in_registry(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that required_scope is recorded in the registry metadata."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        for call in mock_registry.record.call_args_list:
            meta = call[1].get("meta", {}) or {}
            fastmcp_internal = meta.get("fastmcp", {}).get("_internal", {})
            assert "required_scope" in fastmcp_internal, f"Missing required_scope for {call[1].get('uri')}"

    async def test_ignores_non_get_methods(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that POST/PUT/DELETE endpoints are not registered."""
        spec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "post": {"summary": "Create repo", "operationId": "createRepo"},
                    "put": {"summary": "Update repo", "operationId": "updateRepo"},
                }
            }
        }
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, mock_registry)

        # Should not register any resources (no GET)
        mock_mcp.resource.assert_not_called()
        mock_registry.record.assert_not_called()

    async def test_handles_empty_spec(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that empty spec doesn't crash."""
        spec = {"paths": {}}
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, mock_registry)
        mock_mcp.resource.assert_not_called()
        mock_registry.record.assert_not_called()


class TestFindMatchingTokenScopes:
    """Tests for the _find_matching_token_scopes pure helper."""

    def test_matches_token_by_last_eight(self):
        tokens = [
            {"id": 1, "name": "test", "token_last_eight": "last8xyz", "scopes": ["read:repo", "write:issue"]},
        ]
        result = _find_matching_token_scopes(tokens, "any-prefix-last8xyz")
        assert result == ["read:repo", "write:issue"]

    def test_returns_sorted_scopes(self):
        tokens = [
            {"id": 1, "name": "test", "token_last_eight": "deadbeef", "scopes": ["write:issue", "read:repo", "sudo"]},
        ]
        result = _find_matching_token_scopes(tokens, "prefix-deadbeef")
        assert result == ["read:repo", "sudo", "write:issue"]

    def test_returns_none_when_no_match(self):
        tokens = [
            {"id": 1, "name": "t1", "token_last_eight": "aaaaaaaa", "scopes": ["sudo"]},
        ]
        result = _find_matching_token_scopes(tokens, "prefix-bbbbbbbb")
        assert result is None

    def test_returns_none_when_scopes_field_missing(self):
        tokens = [
            {"id": 1, "name": "test", "token_last_eight": "deadbeef"},
        ]
        result = _find_matching_token_scopes(tokens, "prefix-deadbeef")
        assert result is None

    def test_returns_none_when_scopes_is_not_a_list(self):
        tokens = [
            {"id": 1, "name": "test", "token_last_eight": "deadbeef", "scopes": "sudo"},
        ]
        result = _find_matching_token_scopes(tokens, "prefix-deadbeef")
        assert result is None

    def test_returns_none_for_empty_list(self):
        result = _find_matching_token_scopes([], "prefix-anything")
        assert result is None

    def test_skips_non_dict_tokens(self):
        tokens = [
            "not a dict",
            {"id": 1, "name": "test", "token_last_eight": "deadbeef", "scopes": ["read:repo"]},
        ]
        result = _find_matching_token_scopes(tokens, "prefix-deadbeef")
        assert result == ["read:repo"]


class TestRegisterCustomResources:
    """Tests for register_custom_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    async def test_registers_all_custom_resources(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that all expected custom resources are registered."""
        register_custom_resources(mock_mcp, mock_gitea_client, mock_registry)
        assert mock_mcp.resource.call_count == 11

    async def test_custom_resources_have_expected_uris(
        self, mock_mcp, mock_gitea_client, mock_registry
    ):
        """Test that the 11 custom resources have the expected URI templates."""
        register_custom_resources(mock_mcp, mock_gitea_client, mock_registry)
        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]
        expected = [
            "gitea://repos/{owner}/{repo}",
            "gitea://repos/{owner}/{repo}/readme",
            "gitea://repos/{owner}/{repo}/issues{?state}",
            "gitea://repos/{owner}/{repo}/pulls{?state}",
            "gitea://repos/{owner}/{repo}/files/{path*}",
            "gitea://repos/{owner}/{repo}/releases",
            "gitea://users/{username}",
            "gitea://user",
            "gitea://orgs/{orgname}",
            "gitea://version",
            "gitea://token/scopes",
        ]
        for template in expected:
            assert template in uri_templates

    async def test_each_custom_resource_recorded_in_registry(
        self, mock_mcp, mock_gitea_client, mock_registry
    ):
        """Test that registry.record is called once per resource."""
        register_custom_resources(mock_mcp, mock_gitea_client, mock_registry)
        assert mock_registry.record.call_count == 11

    async def test_custom_resources_carry_required_scope(
        self, mock_mcp, mock_gitea_client, mock_registry
    ):
        """Test that all custom resources include required_scope in registry metadata."""
        register_custom_resources(mock_mcp, mock_gitea_client, mock_registry)
        for call in mock_registry.record.call_args_list:
            meta = call[1].get("meta", {}) or {}
            fastmcp_internal = meta.get("fastmcp", {}).get("_internal", {})
            assert "required_scope" in fastmcp_internal, f"Missing required_scope for {call[1].get('uri')}"


class TestResourceFormatters:
    """Tests for other formatting functions."""

    def test_format_issues_markdown_empty(self):
        """Test empty issues list."""
        from gitea_mcp_server.resources.format import _format_issues_markdown

        result = _format_issues_markdown([], title="Test Issues")
        assert "# Test Issues" in result
        assert "No issues found." in result

    def test_format_pulls_markdown_with_data(self):
        """Test pull request formatting."""
        from gitea_mcp_server.resources.format import _format_pulls_markdown

        pull = {
            "number": 1,
            "title": "Test PR",
            "state": "open",
            "user": {"login": "contributor"},
            "created_at": "2024-01-01T00:00:00Z",
            "base": {"label": "main"},
            "head": {"label": "feature"},
            "comments": 5,
            "html_url": "https://example.com/pr/1",
        }
        result = _format_pulls_markdown([pull])

        assert "# Pull Requests" in result
        assert "## PR #1: Test PR" in result
        assert "**State**: open" in result
        assert "**Base**: main" in result

    def test_format_user_markdown_regular_user(self):
        """Test user profile formatting."""
        from gitea_mcp_server.resources.format import _format_user_markdown

        user = {
            "login": "johndoe",
            "full_name": "John Doe",
            "html_url": "https://example.com/johndoe",
            "public_repos": 10,
            "followers_count": 5,
            "following_count": 3,
            "created_at": "2024-01-01T00:00:00Z",
            "bio": "Software developer",
            "location": "NYC",
            "website": "https://johndoe.com",
        }
        result = _format_user_markdown(user)

        assert "# johndoe" in result
        assert "**Name**: John Doe" in result
        assert "| Public Repos | 10 |" in result
        assert "**Bio**: Software developer" in result

    def test_format_user_markdown_organization(self):
        """Test organization profile formatting."""
        from gitea_mcp_server.resources.format import _format_user_markdown

        org = {
            "login": "myorg",
            "type": "Organization",
            "html_url": "https://example.com/myorg",
            "public_repos": 25,
            "description": "A test organization",
        }
        result = _format_user_markdown(org)

        assert "# myorg" in result
        assert "| Type | Organization |" in result


class TestCustomResourceErrorHandling:
    """Tests for custom resource error handling."""

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_get_repository_404_raises_resource_error(self, mock_gitea_client):
        """Test resource_handler raises ResourceError with NOT_FOUND on 404."""
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("repository", "{owner}/{repo}", "Repository '{owner}/{repo}' not found")
        async def get_repository(owner: str, repo: str, gitea_client):
            data = await gitea_client.request("GET", f"/repos/{owner}/{repo}")
            if isinstance(data, str):
                return data
            return data

        mock_gitea_client.request = AsyncMock(
            side_effect=GiteaAPIError("Not found", status_code=HTTP_STATUS_NOT_FOUND)
        )

        with pytest.raises(ResourceError) as exc_info:
            await get_repository("owner", "repo", gitea_client=mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Repository 'owner/repo' not found" in error_data["message"]
        assert error_data["resource_type"] == "repository"
        assert error_data["resource_id"] == "owner/repo"

    async def test_get_file_404_raises_resource_error(self, mock_gitea_client):
        """Test resource_handler raises ResourceError with NOT_FOUND on 404."""
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("file", "{owner}/{repo}/{path}", "File '{path}' not found")
        async def get_file(owner: str, repo: str, path: str, gitea_client):
            data = await gitea_client.request("GET", f"/repos/{owner}/{repo}/contents/{path}")
            if isinstance(data, str):
                return data
            return data

        mock_gitea_client.request = AsyncMock(
            side_effect=GiteaAPIError("Not found", status_code=HTTP_STATUS_NOT_FOUND)
        )

        with pytest.raises(ResourceError) as exc_info:
            await get_file("owner", "repo", "path/to/file", gitea_client=mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "File 'path/to/file' not found" in error_data["message"]
        assert error_data["resource_type"] == "file"
        assert error_data["resource_id"] == "owner/repo/path/to/file"

    async def test_list_repo_issues_invalid_state_raises_validation_error(self, mock_gitea_client):
        """Test resource_handler raises ResourceError with VALIDATION_ERROR for invalid state."""
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("issues", "{owner}/{repo}", "Resource not found: {owner}/{repo}")
        async def list_repo_issues(owner: str, repo: str, gitea_client, state: str = "open"):
            valid_states = {"open", "closed", "all"}
            if state not in valid_states:
                raise ResourceError(
                    {
                        "code": "VALIDATION_ERROR",
                        "message": f"Invalid state parameter: '{state}'",
                        "resource_type": "issues",
                        "resource_id": f"{owner}/{repo}",
                    }
                )
            data = await gitea_client.request("GET", f"/repos/{owner}/{repo}/issues")
            if isinstance(data, str):
                return data
            return data

        with pytest.raises(ResourceError) as exc_info:
            await list_repo_issues("owner", "repo", gitea_client=mock_gitea_client, state="invalid")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "VALIDATION_ERROR"
        assert "Invalid state parameter: 'invalid'" in error_data["message"]
        assert error_data["resource_type"] == "issues"
        assert error_data["resource_id"] == "owner/repo"


class TestDeriveResourceName:
    """Tests for _derive_resource_name helper."""

    def test_uses_operation_id_camel_case(self):
        """Test camelCase operationId is converted to snake_case."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "getRepo"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "get_repo"

    def test_uses_operation_id_snake_case(self):
        """Test snake_case operationId is kept as-is."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "issue_get_issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "issue_get_issue"

    def test_preserves_multi_word_snake_case(self):
        """Test multi-word snake_case is preserved."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "org_list_members"}
        name = _derive_resource_name(operation, "/orgs/{org}/members")
        assert name == "org_list_members"

    def test_falls_back_to_path_when_no_operation_id(self):
        """Test fallback when operationId is missing."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"summary": "Get an issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        # Path segments sans path params: repos, issues
        assert name == "repos_issues"

    def test_handles_empty_operation_id(self):
        """Test fallback when operationId is empty string."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": ""}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "repos_issues"

    def test_handles_complex_camel_case(self):
        """Test complex camelCase with multiple words."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "issueCreateIssueComment"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}/comments")
        assert name == "issue_create_issue_comment"

    def test_handles_leading_uppercase(self):
        """Test leading uppercase in camelCase like 'RepoGet'."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "RepoGet"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "repo_get"


class TestAutoGeneratedResourceErrors:
    """Tests for auto-generated resource error handling."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    async def test_404_raises_structured_error(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test auto-generated resource raises ResourceError with proper structure on 404."""
        spec = {
            "paths": {
                "/test/{id}": {
                    "get": {
                        "summary": "Test endpoint",
                        "operationId": "testEndpoint",
                        "parameters": [
                            {
                                "name": "id",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            }
                        ],
                    }
                }
            }
        }

        # Track registered functions
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, spec, mock_registry, skip_uris=set()
        )

        assert len(registered) == 1
        uri, resource_func = registered[0]
        assert uri == "gitea://test/{id}"

        # Simulate 404 error from client
        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(HTTP_STATUS_NOT_FOUND))

        with pytest.raises(ResourceError) as exc_info:
            await resource_func(id="123")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Resource not found: /test/123" in error_data["message"]
        assert error_data["resource_type"] == "api"
        assert error_data["resource_id"] == "/test/123"


class TestFormatterGaps:
    """Tests for missing formatter edge cases."""

    def test_format_issues_markdown_with_total(self):
        issues = [
            {
                "number": 1,
                "title": "Bug",
                "state": "open",
                "user": {"login": "dev1"},
                "created_at": "2024-01-01T00:00:00Z",
                "comments": 0,
                "labels": [],
                "html_url": "https://example.com/issue/1",
            }
        ]
        result = _format_issues_markdown(issues, title="Open Issues", total=42)

        assert "Showing 1 of 42 total issues" in result
        assert "## #1: Bug" in result

    def test_format_pulls_markdown_empty(self):
        result = _format_pulls_markdown([], title="Pull Requests")

        assert "# Pull Requests" in result
        assert "Showing 0 pull requests" in result
        assert "No pull requests found." in result

    def test_format_release_markdown_full(self):
        release = {
            "tag_name": "v1.0.0",
            "name": "Version 1.0.0",
            "draft": False,
            "prerelease": False,
            "created_at": "2024-01-01T00:00:00Z",
            "published_at": "2024-01-02T00:00:00Z",
            "body": "Release notes here",
        }
        result = _format_release_markdown(release)

        assert "# v1.0.0" in result
        assert "**Title**: Version 1.0.0" in result
        assert "**Draft**: No" in result
        assert "**Prerelease**: No" in result
        assert "Release notes here" in result

    def test_format_release_markdown_missing_name(self):
        release = {
            "tag_name": "v1.0.0",
            "draft": False,
            "prerelease": False,
            "created_at": "2024-01-01T00:00:00Z",
            "published_at": "2024-01-02T00:00:00Z",
            "body": "Body",
        }
        result = _format_release_markdown(release)

        assert "**Title**: v1.0.0" in result

    def test_format_release_markdown_missing_body(self):
        release = {
            "tag_name": "v1.0.0",
            "name": "Version 1.0.0",
            "draft": False,
            "prerelease": False,
            "created_at": "2024-01-01T00:00:00Z",
            "published_at": "2024-01-02T00:00:00Z",
        }
        result = _format_release_markdown(release)

        assert "No description provided." in result

    def test_format_release_markdown_draft_prerelease(self):
        release = {
            "tag_name": "v2.0.0-beta",
            "name": "Beta",
            "draft": True,
            "prerelease": True,
            "created_at": "2024-06-01T00:00:00Z",
            "published_at": "2024-06-02T00:00:00Z",
            "body": "Beta release",
        }
        result = _format_release_markdown(release)

        assert "**Draft**: Yes" in result
        assert "**Prerelease**: Yes" in result

    def test_build_server_info_markdown(self):
        spec = {
            "info": {
                "title": "Gitea API",
                "version": "1.21.0",
                "description": "Gitea API description.",
            }
        }
        result = _build_server_info_markdown(spec)

        assert "**Server Type**: Gitea API" in result
        assert "**API Version**: 1.21.0" in result
        assert "## Description" in result
        assert "Gitea API description." in result

    def test_build_server_info_markdown_no_description(self):
        spec = {"info": {"title": "Gitea API", "version": "1.21.0"}}
        result = _build_server_info_markdown(spec)

        assert "**Server Type**: Gitea API" in result
        assert "## Description" not in result

    def test_build_server_info_markdown_missing_info(self):
        result = _build_server_info_markdown({})

        assert "**Server Type**: Unknown" in result
        assert "**API Version**: Unknown" in result

    def test_handle_not_found_non_404_passes_through(self):
        exc = GiteaAPIError("Internal error", status_code=500)

        _handle_not_found(exc, "test", "123")

    def test_handle_not_found_missing_status_code_passes_through(self):
        exc = ValueError("Some error")

        _handle_not_found(exc, "test", "123")

    def test_handle_not_found_converts_404_with_custom_message(self):
        exc = GiteaAPIError("Not found", status_code=404)

        with pytest.raises(ResourceError) as exc_info:
            _handle_not_found(exc, "test", "123", "Custom message")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert error_data["message"] == "Custom message"
        assert error_data["resource_type"] == "test"
        assert error_data["resource_id"] == "123"

    def test_handle_not_found_converts_404_with_default_message(self):
        exc = GiteaAPIError("Not found", status_code=404)

        with pytest.raises(ResourceError) as exc_info:
            _handle_not_found(exc, "test", "123")

        error_data = exc_info.value.args[0]
        assert error_data["message"] == "Resource not found: 123"


class TestResourceHandlerDecorator:
    """Tests for the resource_handler decorator."""

    @pytest.fixture
    def mock_gitea_client(self):
        return AsyncMock()

    async def test_wraps_successful_response(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("test_type", "{item_id}", "Item '{item_id}' not found.")
        async def my_resource(item_id: str, gitea_client):
            data = await gitea_client.request("GET", f"/items/{item_id}")
            if isinstance(data, str):
                return data
            return f"Formatted: {data}"

        mock_gitea_client.request = AsyncMock(return_value={"name": "test"})
        result = await my_resource(item_id="abc", gitea_client=mock_gitea_client)
        assert result == "Formatted: {'name': 'test'}"
        mock_gitea_client.request.assert_called_once_with("GET", "/items/abc")

    async def test_passes_through_string_response(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("test_type", "{item_id}", "Item '{item_id}' not found.")
        async def my_resource(item_id: str, gitea_client):
            data = await gitea_client.request("GET", f"/items/{item_id}")
            if isinstance(data, str):
                return data
            return f"Formatted: {data}"

        mock_gitea_client.request = AsyncMock(return_value="error string")
        result = await my_resource(item_id="abc", gitea_client=mock_gitea_client)
        assert result == "error string"

    async def test_404_converts_to_resource_error(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("test_type", "{item_id}", "Item '{item_id}' not found.")
        async def my_resource(item_id: str, gitea_client):
            data = await gitea_client.request("GET", f"/items/{item_id}")
            if isinstance(data, str):
                return data
            return f"Formatted: {data}"

        class MockGiteaError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(
            side_effect=MockGiteaError(HTTP_STATUS_NOT_FOUND)
        )

        with pytest.raises(ResourceError) as exc_info:
            await my_resource(item_id="abc", gitea_client=mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Item 'abc' not found." in error_data["message"]
        assert error_data["resource_type"] == "test_type"
        assert error_data["resource_id"] == "abc"

    async def test_non_404_passed_through(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("test_type", "{item_id}", "Item '{item_id}' not found.")
        async def my_resource(item_id: str, gitea_client):
            data = await gitea_client.request("GET", f"/items/{item_id}")
            if isinstance(data, str):
                return data
            return f"Formatted: {data}"

        mock_gitea_client.request = AsyncMock(side_effect=ValueError("boom"))

        with pytest.raises(ValueError, match="boom"):
            await my_resource(item_id="abc", gitea_client=mock_gitea_client)

    async def test_preserves_function_metadata(self):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("test_type", "{item_id}", "Item '{item_id}' not found.")
        async def my_resource(item_id: str, gitea_client):
            """My test resource."""
            return "ok"

        assert my_resource.__name__ == "my_resource"
        assert my_resource.__doc__ == "My test resource."

    async def test_positional_args_resolved_correctly(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("repo", "{owner}/{repo}", "Not found: {owner}/{repo}")
        async def my_resource(owner: str, repo: str, gitea_client):
            return f"OK: {owner}/{repo}"

        mock_gitea_client.request = AsyncMock(return_value={})
        result = await my_resource("user", "my-repo", gitea_client=mock_gitea_client)
        assert result == "OK: user/my-repo"

    async def test_positional_args_error_formatting(self, mock_gitea_client):
        from gitea_mcp_server.resources.custom import resource_handler

        @resource_handler("repo", "{owner}/{repo}", "Repo '{owner}/{repo}' missing.")
        async def my_resource(owner: str, repo: str, gitea_client):
            data = await gitea_client.request("GET", f"/repos/{owner}/{repo}")
            if isinstance(data, str):
                return data
            return f"Formatted: {data}"

        class MockGiteaError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=MockGiteaError(HTTP_STATUS_NOT_FOUND))
        with pytest.raises(ResourceError) as exc_info:
            await my_resource("user", "my-repo", gitea_client=mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["resource_type"] == "repo"
        assert error_data["resource_id"] == "user/my-repo"
        assert "Repo 'user/my-repo' missing." in error_data["message"]
