"""Tests for the resources module."""

import base64
import json
from unittest.mock import AsyncMock, MagicMock

import pytest
from fastmcp.exceptions import ResourceError
from mcp.server.fastmcp import FastMCP

from gitea_mcp_server.constants import HTTP_STATUS_NOT_FOUND
from gitea_mcp_server.resources.auto import register_auto_generated_resources
from gitea_mcp_server.resources.custom import (
    get_file,
    get_readme,
    get_repository,
    list_repo_issues,
    register_custom_resources,
)
from gitea_mcp_server.resources.format import _format_datetime, _format_repo_markdown
from gitea_mcp_server.resources.registry import ResourceRegistry


class TestFormatDateTime:
    """Tests for _format_datetime."""

    def test_formats_iso_datetime(self):
        """Test ISO datetime string is formatted correctly."""
        dt = "2024-01-15T10:30:00Z"
        result = _format_datetime(dt)
        assert result == "2024-01-15 10:30:00 UTC"

    def test_handles_none(self):
        """Test None returns N/A."""
        assert _format_datetime(None) == "N/A"

    def test_handles_empty_string(self):
        """Test empty string returns N/A."""
        assert _format_datetime("") == "N/A"

    def test_handles_invalid_format(self):
        """Test invalid format returns original string."""
        assert _format_datetime("not a date") == "not a date"


class TestFormatRepoMarkdown:
    """Tests for _format_repo_markdown."""

    def test_formats_repo_completely(self):
        """Test repository is formatted with all fields."""
        repo = {
            "full_name": "owner/repo",
            "description": "Test repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
            "default_branch": "main",
            "stargazers_count": 42,
            "forks_count": 10,
            "open_issues_count": 5,
            "size": 1024,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-15T00:00:00Z",
            "topics": ["test", "example"],
            "license": {"name": "MIT"},
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "**Description**: Test repo" in result
        assert "| Owner | owner |" in result
        assert "| Stars | 42 |" in result
        assert "**Topics**: test, example" in result
        assert "**License**: MIT" in result

    def test_handles_missing_fields(self):
        """Test repo with missing optional fields."""
        repo = {
            "full_name": "owner/repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "No description" in result
        assert "None" in result  # topics, license etc.


class TestRegisterAutoGeneratedResources:
    """Tests for register_auto_generated_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        # Mock the resource decorator to track registrations
        mcp.resource = MagicMock(return_value=lambda func: func)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    @pytest.fixture
    def openapi_spec_with_get(self):
        """OpenAPI spec with a simple GET endpoint.

        Uses realistic paths without a /gitea prefix -- matches the actual
        Gitea/Forgejo OpenAPI spec at /swagger.v1.json.
        The URI scheme is always gitea:// for consistent namespacing.
        """
        return {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repository information",
                        "description": "Get details about a repository",
                        "operationId": "getRepo",
                        "tags": ["repository"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List repository issues",
                        "operationId": "listRepoIssues",
                        "tags": ["repository", "issue"],
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "state",
                                "in": "query",
                                "required": False,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
            }
        }

    async def test_registers_resources_for_get_endpoints(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that GET endpoints are registered as resources."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        # Should have called resource decorator twice (2 GET endpoints)
        assert mock_mcp.resource.call_count == 2

        # Check URI templates
        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in uri_templates
        assert "gitea://repos/{owner}/{repo}/issues" in uri_templates

        # Verify registry.record was called for each
        assert mock_registry.record.call_count == 2
        # Check records have correct URIs
        recorded_uris = [call[1]["uri"] for call in mock_registry.record.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in recorded_uris
        assert "gitea://repos/{owner}/{repo}/issues" in recorded_uris

    async def test_resource_function_has_docstring(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources have proper docstrings."""
        # Track registered functions
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        # Find the resource for /repos/{owner}/{repo}
        repo_entry = next(r for r in registered if r[0] == "gitea://repos/{owner}/{repo}")
        resource_func = repo_entry[1]

        assert resource_func.__doc__ is not None
        assert "Get repository information" in resource_func.__doc__

    async def test_resources_have_meaningful_names(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources get names from operationId."""
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, kwargs.get("name", func.__name__)))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        names = {uri: name for uri, name in registered}
        # operationId "getRepo" -> name "get_repo"
        assert names["gitea://repos/{owner}/{repo}"] == "get_repo"
        # operationId "listRepoIssues" -> name "list_repo_issues"
        assert names["gitea://repos/{owner}/{repo}/issues"] == "list_repo_issues"

    async def test_resources_have_required_scope_in_meta(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that auto-generated resources carry required_scope in meta passed to mcp.resource()."""
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, kwargs.get("meta", {})))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        metas = {uri: meta for uri, meta in registered}
        repo_meta = metas["gitea://repos/{owner}/{repo}"]
        issues_meta = metas["gitea://repos/{owner}/{repo}/issues"]
        assert repo_meta.get("fastmcp", {}).get("_internal", {}).get("required_scope") == "read:repository"
        # issues endpoint has tags ["repository", "issue"] -> set iteration order is non-deterministic
        assert issues_meta.get("fastmcp", {}).get("_internal", {}).get("required_scope") in (
            "read:issue",
            "read:repository",
        )

    async def test_resources_record_required_scope_in_registry(
        self, mock_mcp, mock_gitea_client, mock_registry, openapi_spec_with_get
    ):
        """Test that required_scope is recorded in the registry metadata."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, mock_registry, skip_uris=set()
        )

        for call in mock_registry.record.call_args_list:
            meta = call[1].get("meta", {}) or {}
            fastmcp_internal = meta.get("fastmcp", {}).get("_internal", {})
            assert "required_scope" in fastmcp_internal, f"Missing required_scope for {call[1].get('uri')}"

    async def test_ignores_non_get_methods(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that POST/PUT/DELETE endpoints are not registered."""
        spec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "post": {"summary": "Create repo", "operationId": "createRepo"},
                    "put": {"summary": "Update repo", "operationId": "updateRepo"},
                }
            }
        }
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, mock_registry)

        # Should not register any resources (no GET)
        mock_mcp.resource.assert_not_called()
        mock_registry.record.assert_not_called()

    async def test_handles_empty_spec(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that empty spec doesn't crash."""
        spec = {"paths": {}}
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, mock_registry)
        mock_mcp.resource.assert_not_called()
        mock_registry.record.assert_not_called()


class TestGetActiveTokenScopes:
    """Tests for the get_active_token_scopes resource function."""

    @pytest.mark.asyncio
    async def test_returns_scopes_for_matched_token(self):
        from gitea_mcp_server.resources.custom import get_active_token_scopes

        client = AsyncMock()
        token_val = "test-token-xxxxxx_last8"
        client._config.token = token_val
        client.request = AsyncMock(
            side_effect=[
                {"login": "dev2"},
                [
                    {"id": 1, "name": "test", "token_last_eight": token_val[-8:], "scopes": ["read:repo", "write:issue"]},
                    {"id": 2, "name": "other", "token_last_eight": "00000000", "scopes": ["sudo"]},
                ],
            ]
        )

        result = await get_active_token_scopes(gitea_client=client)

        assert result is not None
        data = json.loads(result)
        assert set(data["scopes"]) == {"read:repo", "write:issue"}

    @pytest.mark.asyncio
    async def test_returns_null_when_no_token_match(self):
        from gitea_mcp_server.resources.custom import get_active_token_scopes

        client = AsyncMock()
        client._config.token = "unknown-token"
        client.request = AsyncMock(
            side_effect=[
                {"login": "dev2"},
                [
                    {"id": 1, "name": "t1", "token_last_eight": "ffffffff", "scopes": ["sudo"]},
                ],
            ]
        )

        result = await get_active_token_scopes(gitea_client=client)

        assert result is not None
        data = json.loads(result)
        assert data["scopes"] is None

    @pytest.mark.asyncio
    async def test_handles_api_failure(self):
        from gitea_mcp_server.resources.custom import get_active_token_scopes

        client = AsyncMock()
        client.request = AsyncMock(side_effect=Exception("API error"))

        result = await get_active_token_scopes(gitea_client=client)

        assert result is not None
        data = json.loads(result)
        assert data["scopes"] is None


class TestRegisterCustomResources:
    """Tests for register_custom_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    async def test_registers_all_custom_resources(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test that all expected custom resources are registered."""
        register_custom_resources(mock_mcp, mock_gitea_client, mock_registry)

        # Should register 11 custom resources (9 original + gitea://version + gitea://token/scopes)
        assert mock_mcp.resource.call_count == 11

        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]

        expected = [
            "gitea://repos/{owner}/{repo}",
            "gitea://repos/{owner}/{repo}/readme",
            "gitea://repos/{owner}/{repo}/issues{?state}",
            "gitea://repos/{owner}/{repo}/pulls{?state}",
            "gitea://repos/{owner}/{repo}/files/{path}",
            "gitea://repos/{owner}/{repo}/releases",
            "gitea://users/{username}",
            "gitea://user",
            "gitea://orgs/{orgname}",
            "gitea://version",
            "gitea://token/scopes",
        ]
        for template in expected:
            assert template in uri_templates

        # Verify registry.record called for each
        assert mock_registry.record.call_count == 11

        # Verify all custom resources carry required_scope in meta
        for call in mock_registry.record.call_args_list:
            meta = call[1].get("meta", {}) or {}
            fastmcp_internal = meta.get("fastmcp", {}).get("_internal", {})
            assert "required_scope" in fastmcp_internal, f"Missing required_scope for {call[1].get('uri')}"


class TestResourceFormatters:
    """Tests for other formatting functions."""

    def test_format_issues_markdown_empty(self):
        """Test empty issues list."""
        from gitea_mcp_server.resources.format import _format_issues_markdown

        result = _format_issues_markdown([], title="Test Issues")
        assert "# Test Issues" in result
        assert "No issues found." in result

    def test_format_pulls_markdown_with_data(self):
        """Test pull request formatting."""
        from gitea_mcp_server.resources.format import _format_pulls_markdown

        pull = {
            "number": 1,
            "title": "Test PR",
            "state": "open",
            "user": {"login": "contributor"},
            "created_at": "2024-01-01T00:00:00Z",
            "base": {"label": "main"},
            "head": {"label": "feature"},
            "comments": 5,
            "html_url": "https://example.com/pr/1",
        }
        result = _format_pulls_markdown([pull])

        assert "# Pull Requests" in result
        assert "## PR #1: Test PR" in result
        assert "**State**: open" in result
        assert "**Base**: main" in result

    def test_format_user_markdown_regular_user(self):
        """Test user profile formatting."""
        from gitea_mcp_server.resources.format import _format_user_markdown

        user = {
            "login": "johndoe",
            "full_name": "John Doe",
            "html_url": "https://example.com/johndoe",
            "public_repos": 10,
            "followers_count": 5,
            "following_count": 3,
            "created_at": "2024-01-01T00:00:00Z",
            "bio": "Software developer",
            "location": "NYC",
            "website": "https://johndoe.com",
        }
        result = _format_user_markdown(user)

        assert "# johndoe" in result
        assert "**Name**: John Doe" in result
        assert "| Public Repos | 10 |" in result
        assert "**Bio**: Software developer" in result

    def test_format_user_markdown_organization(self):
        """Test organization profile formatting."""
        from gitea_mcp_server.resources.format import _format_user_markdown

        org = {
            "login": "myorg",
            "type": "Organization",
            "html_url": "https://example.com/myorg",
            "public_repos": 25,
            "description": "A test organization",
        }
        result = _format_user_markdown(org)

        assert "# myorg" in result
        assert "| Type | Organization |" in result


class TestGetReadme:
    """Tests for get_readme function."""

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_base64_content(self, mock_gitea_client):
        """Test README with base64 encoded content."""
        # Prepare base64 encoded content
        readme_content = "# Test README\n\nThis is a test."
        encoded_content = base64.b64encode(readme_content.encode("utf-8")).decode("utf-8")

        mock_gitea_client.request = AsyncMock(
            return_value={"content": encoded_content, "encoding": "base64"}
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content
        mock_gitea_client.request.assert_called_once_with(
            "GET", "/repos/owner/repo/contents/README.md"
        )

    async def test_plain_text_content(self, mock_gitea_client):
        """Test README with plain text content (no base64 encoding)."""
        readme_content = "# Plain README\n\nNo encoding."

        mock_gitea_client.request = AsyncMock(
            return_value={
                "content": readme_content,
                "encoding": "text",  # or any non-base64 encoding
            }
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content

    async def test_missing_content_field(self, mock_gitea_client):
        """Test README response with missing content field."""
        mock_gitea_client.request = AsyncMock(
            return_value={
                "encoding": "base64"
                # content field is missing
            }
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        # Should return empty string when content is missing
        assert result == ""

    async def test_string_response(self, mock_gitea_client):
        """Test README when API returns a string directly."""
        readme_content = "# Direct string README"

        mock_gitea_client.request = AsyncMock(return_value=readme_content)

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content

    async def test_404_error(self, mock_gitea_client):
        """Test README raises ResourceError with NOT_FOUND on 404."""

        # Create an exception with status_code attribute
        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(HTTP_STATUS_NOT_FOUND))

        with pytest.raises(ResourceError) as exc_info:
            await get_readme("owner", "repo", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "README not found" in error_data["message"]
        assert error_data["resource_type"] == "readme"
        assert error_data["resource_id"] == "owner/repo"

    async def test_other_errors_raised(self, mock_gitea_client):
        """Test that non-404 errors are raised."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(500))

        with pytest.raises(GiteaAPIError) as exc_info:
            await get_readme("owner", "repo", mock_gitea_client)

        assert exc_info.value.status_code == 500

    async def test_non_dict_non_string_response(self, mock_gitea_client):
        """Test handling of unexpected response types."""
        mock_gitea_client.request = AsyncMock(return_value=12345)

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == "12345"


class TestCustomResourceErrorHandling:
    """Tests for custom resource error handling."""

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_get_repository_404_raises_resource_error(self, mock_gitea_client):
        """Test get_repository raises ResourceError with NOT_FOUND on 404."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(HTTP_STATUS_NOT_FOUND))

        with pytest.raises(ResourceError) as exc_info:
            await get_repository("owner", "repo", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Repository 'owner/repo' not found" in error_data["message"]
        assert error_data["resource_type"] == "repository"
        assert error_data["resource_id"] == "owner/repo"

    async def test_get_file_404_raises_resource_error(self, mock_gitea_client):
        """Test get_file raises ResourceError with NOT_FOUND on 404."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(HTTP_STATUS_NOT_FOUND))

        with pytest.raises(ResourceError) as exc_info:
            await get_file("owner", "repo", "path/to/file", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "File 'path/to/file' not found" in error_data["message"]
        assert error_data["resource_type"] == "file"
        assert error_data["resource_id"] == "owner/repo/path/to/file"

    async def test_list_repo_issues_invalid_state_raises_validation_error(self, mock_gitea_client):
        """Test list_repo_issues raises ResourceError with VALIDATION_ERROR for invalid state."""

        with pytest.raises(ResourceError) as exc_info:
            await list_repo_issues("owner", "repo", mock_gitea_client, state="invalid")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "VALIDATION_ERROR"
        assert "Invalid state parameter: 'invalid'" in error_data["message"]
        assert error_data["resource_type"] == "issues"
        assert error_data["resource_id"] == "owner/repo"


class TestDeriveResourceName:
    """Tests for _derive_resource_name helper."""

    def test_uses_operation_id_camel_case(self):
        """Test camelCase operationId is converted to snake_case."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "getRepo"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "get_repo"

    def test_uses_operation_id_snake_case(self):
        """Test snake_case operationId is kept as-is."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "issue_get_issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "issue_get_issue"

    def test_preserves_multi_word_snake_case(self):
        """Test multi-word snake_case is preserved."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "org_list_members"}
        name = _derive_resource_name(operation, "/orgs/{org}/members")
        assert name == "org_list_members"

    def test_falls_back_to_path_when_no_operation_id(self):
        """Test fallback when operationId is missing."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"summary": "Get an issue"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        # Path segments sans path params: repos, issues
        assert name == "repos_issues"

    def test_handles_empty_operation_id(self):
        """Test fallback when operationId is empty string."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": ""}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}")
        assert name == "repos_issues"

    def test_handles_complex_camel_case(self):
        """Test complex camelCase with multiple words."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "issueCreateIssueComment"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}/issues/{index}/comments")
        assert name == "issue_create_issue_comment"

    def test_handles_leading_uppercase(self):
        """Test leading uppercase in camelCase like 'RepoGet'."""
        from gitea_mcp_server.resources.auto import _derive_resource_name

        operation = {"operationId": "RepoGet"}
        name = _derive_resource_name(operation, "/repos/{owner}/{repo}")
        assert name == "repo_get"


class TestAutoGeneratedResourceErrors:
    """Tests for auto-generated resource error handling."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def mock_registry(self):
        """Create a mock ResourceRegistry."""
        registry = MagicMock(spec=ResourceRegistry)
        return registry

    async def test_404_raises_structured_error(self, mock_mcp, mock_gitea_client, mock_registry):
        """Test auto-generated resource raises ResourceError with proper structure on 404."""
        spec = {
            "paths": {
                "/test/{id}": {
                    "get": {
                        "summary": "Test endpoint",
                        "operationId": "testEndpoint",
                        "parameters": [
                            {
                                "name": "id",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            }
                        ],
                    }
                }
            }
        }

        # Track registered functions
        registered = []

        def track_decorator(uri, **kwargs):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, spec, mock_registry, skip_uris=set()
        )

        assert len(registered) == 1
        uri, resource_func = registered[0]
        assert uri == "gitea://test/{id}"

        # Simulate 404 error from client
        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(HTTP_STATUS_NOT_FOUND))

        with pytest.raises(ResourceError) as exc_info:
            await resource_func(id="123")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Resource not found: /test/123" in error_data["message"]
        assert error_data["resource_type"] == "api"
        assert error_data["resource_id"] == "/test/123"
