"""Tests for gitea_mcp_server.tools.contract — the generic contract spine.

The spine (:func:`~gitea_mcp_server.tools.contract.build_transform_fn`) is
shared by autogenerated and synthetic tools.  These tests exercise it with a
recording executor, independent of any specific backend: virtual-param
extraction, pre-hooks, context resolution, ``_raw_schema`` attachment, and
post-hook formatting.
"""

from __future__ import annotations

import base64
from typing import TYPE_CHECKING, Any

import pytest
from fastmcp.tools.base import Tool, ToolResult

from gitea_mcp_server.tools.contract import build_transform_fn
from gitea_mcp_server.tools.result_pipeline import ExecutionResult
from tests.helpers.spec_fixtures import make_openapi_spec

if TYPE_CHECKING:
    from gitea_mcp_server.models import ViewHints


def _make_tool(
    *,
    raw_schema: dict[str, Any] | None = None,
    response_type: str | None = None,
    view_hints: ViewHints | None = None,
) -> Tool:
    """Minimal Tool whose meta optionally carries display pipeline metadata."""
    meta: dict[str, Any] = {}
    if raw_schema is not None:
        meta["output_schema_raw"] = raw_schema
    if response_type is not None:
        meta["response_type"] = response_type
    if view_hints is not None:
        meta["view_hints"] = view_hints
    return Tool(
        name="test_tool",
        description="A test tool.",
        parameters={"properties": {}},
        meta=meta,
    )


class TestBuildTransformFn:
    """Tests for the generic per-call contract spine."""

    @pytest.mark.asyncio
    async def test_executor_receives_popped_kwargs_and_extracted(self) -> None:
        """Virtual params are popped from kwargs and passed to the executor."""
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool()
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        result = await transform_fn(query="q", page=1, format="json", detail="full")

        assert received["kwargs"] == {"query": "q", "page": 1}
        assert received["extracted"] == {"format": "json", "detail": "full"}
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_context_is_none_outside_session(self) -> None:
        """Executor receives ctx=None when no MCP session is active."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            captured["ctx"] = ctx
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(query="q")

        assert captured["ctx"] is None

    @pytest.mark.asyncio
    async def test_pre_hooks_mutate_kwargs(self) -> None:
        """Pre-hooks run before the executor (content_type base64-encodes content)."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            captured["content"] = kwargs.get("content")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(content="hello", content_type="text")

        assert captured["content"] == base64.b64encode(b"hello").decode()

    @pytest.mark.asyncio
    async def test_invalid_format_rejected_before_executor(self) -> None:
        """An invalid ``format`` fails before the executor — no side effect (#789)."""
        calls = {"n": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["n"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with pytest.raises(ValueError, match="format must be one of"):
            await transform_fn(query="q", format="bogus")

        assert calls["n"] == 0

    @pytest.mark.asyncio
    async def test_invalid_detail_rejected_before_executor(self) -> None:
        """An invalid ``detail`` fails before the executor (#789)."""
        calls = {"n": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["n"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with pytest.raises(ValueError, match="detail must be one of"):
            await transform_fn(query="q", detail="bogus")

        assert calls["n"] == 0

    @pytest.mark.asyncio
    async def test_invalid_content_type_rejected_before_pre_hook(self, monkeypatch: Any) -> None:
        """A bad ``content_type`` is rejected before the pre-hook encodes content.

        Asserts neither the executor nor the pre-hook stage is reached, so the
        rejection genuinely happens before ``content`` could be encoded.
        """
        calls = {"executor": 0, "pre_hooks": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["executor"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        def _spy_pre_hooks(extracted: dict[str, Any], kwargs: dict[str, Any] | None = None) -> None:
            calls["pre_hooks"] += 1

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_pre_hooks", _spy_pre_hooks)

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with pytest.raises(ValueError, match="content_type must be one of"):
            await transform_fn(content="hello", content_type="bogus")

        assert calls == {"executor": 0, "pre_hooks": 0}

    @pytest.mark.asyncio
    async def test_absent_format_uses_spine_default(self) -> None:
        """When ``format`` is omitted, the configured default renders the result."""
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="json")
        result = await transform_fn(query="q")

        assert "format" not in received["extracted"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_raw_schema_attached_for_post_hooks(self, monkeypatch: Any) -> None:
        """tool.meta['output_schema_raw'] reaches the post-hook as _raw_schema."""
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}
        seen: dict[str, Any] = {}

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            seen["extracted"] = dict(extracted)
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data={"name": "x"}, shape="object")

        transform_fn = build_transform_fn(
            _make_tool(raw_schema=raw_schema), executor, default_format="markdown"
        )
        await transform_fn(query="q")

        assert seen["extracted"]["_raw_schema"] == raw_schema

    @pytest.mark.asyncio
    async def test_post_hooks_run_after_executor(self, monkeypatch: Any) -> None:
        """apply_to receives the executor's result and its return value is the tool result."""
        calls: list[str] = []

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls.append("executor")
            return ExecutionResult(data="ok", shape="scalar")

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            calls.append("apply_to")
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        result = await transform_fn(query="q")

        assert calls == ["executor", "apply_to"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_allowlist_restricts_extraction(self) -> None:
        """tool.meta['_virtual_params'] limits which registry params are popped.

        Off-allowlist registry-name keys (e.g. ``fetch_all`` on a format-only
        synthetic tool) stay in kwargs so validation rejects them as unknown
        instead of silently dropping the value.
        """
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool()
        tool.meta = {"_virtual_params": {"format"}}
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        await transform_fn(query="q", format="json", fetch_all=True)

        # format (allowlisted) popped; fetch_all (off-allowlist) left in kwargs.
        assert received["extracted"] == {"format": "json"}
        assert received["kwargs"] == {"query": "q", "fetch_all": True}

    @pytest.mark.asyncio
    async def test_no_allowlist_pops_all_virtual_params(self) -> None:
        """Fallback: a tool without a stamped _virtual_params pops every registry param.

        Autogen tools normally get their allowlist stamped by ``_inject_params``
        (extraction matches injection); this exercises the unstamped fallback
        where ``extract_from(only=None)`` pops every registry param.
        """
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(query="q", format="json", fetch_all=True)

        assert received["extracted"] == {"format": "json", "fetch_all": True}
        assert received["kwargs"] == {"query": "q"}

    @pytest.mark.asyncio
    async def test_autogen_allowlist_leaves_fetch_all_in_kwargs(self) -> None:
        """Autogen tools' stamped allowlist excludes fetch_all → rejected as unknown.

        ``_inject_params`` stamps ``tool.meta["_virtual_params"]`` with the
        actually-injected set (fetch_all is predicate-gated to synthetic
        tools), so extraction leaves it in kwargs for validation to reject
        instead of silently dropping it.
        """
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool()
        # What _inject_params stamps for an autogen tool: visible params that
        # passed injection (format/detail), fetch_all excluded by predicate.
        tool.meta = {"_virtual_params": {"format", "detail"}}
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        await transform_fn(query="q", format="json", fetch_all=True)

        assert received["extracted"] == {"format": "json"}
        assert received["kwargs"] == {"query": "q", "fetch_all": True}

    @pytest.mark.asyncio
    async def test_openapi_spec_forwarded_to_render(self, monkeypatch: Any) -> None:
        """build_transform_fn captures openapi_spec and threads it to render (#759).

        The spec enables root-list item summaries under ``detail=concise``.
        This is the unit lock for the closure threading — without it the
        wiring (``mcp_builder`` → ``build_transform_fn`` → ``render`` →
        collapse) is pinned only by the live suite.
        """
        from gitea_mcp_server.tools import contract as contract_module

        spec = make_openapi_spec()
        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch.setattr(contract_module, "render", _spy_render)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(
            _make_tool(), executor, openapi_spec=spec, default_format="markdown"
        )
        result = await transform_fn(query="q", format="json")

        assert seen["openapi_spec"] is spec
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_openapi_spec_defaults_to_none(self, monkeypatch: Any) -> None:
        """Omitting the spec (unit callers) forwards ``None`` — fallback contract."""
        from gitea_mcp_server.tools import contract as contract_module

        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch.setattr(contract_module, "render", _spy_render)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(query="q", format="json")

        assert seen["openapi_spec"] is None

    @pytest.mark.asyncio
    async def test_execution_result_is_rendered_by_pipeline(self) -> None:
        """Every executor return is rendered by the single result pipeline.

        There is no ToolResult carve-out: the spine renders the executor's
        ``ExecutionResult`` through the pipeline, so ``format=json`` produces
        the envelope in the text channel.
        """
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data={"name": "alpha"}, shape="object")

        transform_fn = build_transform_fn(
            _make_tool(raw_schema=raw_schema), executor, default_format="markdown"
        )
        result = await transform_fn(query="q", format="json")

        assert result.structured_content == {"result": {"name": "alpha"}}


class TestDisplayExtraDerivation:
    """The spine forwards formatter context derived from the call args.

    ``owner``/``repo``/``type`` are real path/query params on the tools whose
    domain formatters use them; the spine surfaces them as the pipeline's
    ``extra`` display input — the same channel as the page/limit capture.
    """

    @staticmethod
    async def _run_transform(
        *,
        tool: Tool | None = None,
        **call_kwargs: Any,
    ) -> dict[str, Any]:
        """Run the spine with a spy on ``render``; return the captured kwargs."""
        from gitea_mcp_server.tools import contract as contract_module

        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch = pytest.MonkeyPatch()
        try:
            monkeypatch.setattr(contract_module, "render", _spy_render)

            async def executor(
                kwargs: dict[str, Any],
                extracted: dict[str, Any] | None,
                ctx: Any,
            ) -> ExecutionResult:
                return ExecutionResult(data=[], shape="list")

            transform_fn = build_transform_fn(
                tool or _make_tool(), executor, default_format="markdown"
            )
            await transform_fn(**call_kwargs)
            return seen
        finally:
            monkeypatch.undo()

    @pytest.mark.asyncio
    async def test_context_keys_forwarded(self) -> None:
        seen = await self._run_transform(owner="o", repo="r", type="pulls", format="json")
        assert seen["extra"] == {"owner": "o", "repo": "r", "type": "pulls"}

    @pytest.mark.asyncio
    async def test_org_context_key_forwarded(self) -> None:
        """Org-scoped tools forward ``org`` as display context (#766)."""
        seen = await self._run_transform(org="mcp-server", format="json")
        assert seen["extra"] == {"org": "mcp-server"}

    @pytest.mark.asyncio
    async def test_partial_context_keys(self) -> None:
        seen = await self._run_transform(owner="o", q="x", format="json")
        assert seen["extra"] == {"owner": "o"}

    @pytest.mark.asyncio
    async def test_no_context_keys_is_none(self) -> None:
        """Tools without repo scope pass ``None`` — formatters use graceful defaults."""
        seen = await self._run_transform(q="x", format="json")
        assert seen["extra"] is None

    @pytest.mark.asyncio
    async def test_response_type_forwarded_from_tool_meta(self) -> None:
        """The spine reads ``tool.meta["response_type"]`` into ``render``."""
        seen = await self._run_transform(tool=_make_tool(response_type="Repository"), format="json")
        assert seen["response_type"] == "Repository"

    @pytest.mark.asyncio
    async def test_view_hints_forwarded_from_tool_meta(self) -> None:
        """The spine reads ``tool.meta["view_hints"]`` into ``render`` (#775)."""
        hints: ViewHints = {"omit": ["url"]}
        seen = await self._run_transform(
            tool=_make_tool(response_type="Repository", view_hints=hints), format="json"
        )
        assert seen["view_hints"] == hints

    @pytest.mark.asyncio
    async def test_absent_view_hints_is_none(self) -> None:
        """A tool without the meta key passes ``None`` — plain schema view."""
        seen = await self._run_transform(format="json")
        assert seen["view_hints"] is None

    @pytest.mark.asyncio
    async def test_absent_response_type_is_none(self) -> None:
        """A tool without the meta key passes ``None`` — generic renderer."""
        seen = await self._run_transform(format="json")
        assert seen["response_type"] is None

    def test_none_values_dropped(self) -> None:
        """A param explicitly set to ``None`` is not forwarded as context."""
        from gitea_mcp_server.tools.contract import _derive_display_extra

        assert _derive_display_extra({"owner": "o", "repo": None}) == {"owner": "o"}
        assert _derive_display_extra({"owner": None}) is None
        assert _derive_display_extra({}) is None
