"""Tests for the resources module."""

import json
import base64
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from mcp.server.fastmcp import FastMCP
from fastmcp.exceptions import ResourceError

from gitea_mcp_server.resources import (
    register_auto_generated_resources,
    register_custom_resources,
    _format_datetime,
    _format_repo_markdown,
    get_readme,
    get_repository,
    list_repo_issues,
    get_file,
)


class TestFormatDateTime:
    """Tests for _format_datetime."""

    def test_formats_iso_datetime(self):
        """Test ISO datetime string is formatted correctly."""
        dt = "2024-01-15T10:30:00Z"
        result = _format_datetime(dt)
        assert result == "2024-01-15 10:30:00 UTC"

    def test_handles_none(self):
        """Test None returns N/A."""
        assert _format_datetime(None) == "N/A"

    def test_handles_empty_string(self):
        """Test empty string returns N/A."""
        assert _format_datetime("") == "N/A"

    def test_handles_invalid_format(self):
        """Test invalid format returns original string."""
        assert _format_datetime("not a date") == "not a date"


class TestFormatRepoMarkdown:
    """Tests for _format_repo_markdown."""

    def test_formats_repo_completely(self):
        """Test repository is formatted with all fields."""
        repo = {
            "full_name": "owner/repo",
            "description": "Test repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
            "default_branch": "main",
            "stargazers_count": 42,
            "forks_count": 10,
            "open_issues_count": 5,
            "size": 1024,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-15T00:00:00Z",
            "topics": ["test", "example"],
            "license": {"name": "MIT"},
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "**Description**: Test repo" in result
        assert "| Owner | owner |" in result
        assert "| Stars | 42 |" in result
        assert "**Topics**: test, example" in result
        assert "**License**: MIT" in result

    def test_handles_missing_fields(self):
        """Test repo with missing optional fields."""
        repo = {
            "full_name": "owner/repo",
            "owner": {"login": "owner"},
            "html_url": "https://example.com/owner/repo",
        }
        result = _format_repo_markdown(repo)

        assert "# owner/repo" in result
        assert "No description" in result
        assert "None" in result  # topics, license etc.


class TestRegisterAutoGeneratedResources:
    """Tests for register_auto_generated_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        # Mock the resource decorator to track registrations
        mcp.resource = MagicMock(return_value=lambda func: func)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    @pytest.fixture
    def openapi_spec_with_get(self):
        """OpenAPI spec with a simple GET endpoint."""
        return {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "get": {
                        "summary": "Get repository information",
                        "description": "Get details about a repository",
                        "operationId": "getRepo",
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
                "/repos/{owner}/{repo}/issues": {
                    "get": {
                        "summary": "List repository issues",
                        "operationId": "listRepoIssues",
                        "parameters": [
                            {
                                "name": "owner",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "repo",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            },
                            {
                                "name": "state",
                                "in": "query",
                                "required": False,
                                "schema": {"type": "string"},
                            },
                        ],
                    }
                },
            }
        }

    async def test_registers_resources_for_get_endpoints(
        self, mock_mcp, mock_gitea_client, openapi_spec_with_get
    ):
        """Test that GET endpoints are registered as resources."""
        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )

        # Should have called resource decorator twice (2 GET endpoints)
        assert mock_mcp.resource.call_count == 2

        # Check URI templates
        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]
        assert "gitea://repos/{owner}/{repo}" in uri_templates
        assert "gitea://repos/{owner}/{repo}/issues" in uri_templates

    async def test_resource_function_has_docstring(
        self, mock_mcp, mock_gitea_client, openapi_spec_with_get
    ):
        """Test that auto-generated resources have proper docstrings."""
        # Track registered functions
        registered = []

        def track_decorator(uri):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(
            mock_mcp, mock_gitea_client, openapi_spec_with_get, skip_uris=set()
        )

        # Find the resource for /repos/{owner}/{repo}
        repo_entry = next(r for r in registered if r[0] == "gitea://repos/{owner}/{repo}")
        resource_func = repo_entry[1]

        assert resource_func.__doc__ is not None
        assert "Get repository information" in resource_func.__doc__

    async def test_ignores_non_get_methods(self, mock_mcp, mock_gitea_client):
        """Test that POST/PUT/DELETE endpoints are not registered."""
        spec = {
            "paths": {
                "/repos/{owner}/{repo}": {
                    "post": {"summary": "Create repo", "operationId": "createRepo"},
                    "put": {"summary": "Update repo", "operationId": "updateRepo"},
                }
            }
        }
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec)

        # Should not register any resources (no GET)
        mock_mcp.resource.assert_not_called()

    async def test_handles_empty_spec(self, mock_mcp, mock_gitea_client):
        """Test that empty spec doesn't crash."""
        spec = {"paths": {}}
        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec)
        mock_mcp.resource.assert_not_called()


class TestRegisterCustomResources:
    """Tests for register_custom_resources."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_registers_all_custom_resources(self, mock_mcp, mock_gitea_client):
        """Test that all expected custom resources are registered."""
        register_custom_resources(mock_mcp, mock_gitea_client)

        # Should register 11 custom resources
        assert mock_mcp.resource.call_count == 11

        uri_templates = [call[0][0] for call in mock_mcp.resource.call_args_list]

        expected = [
            "gitea://repos/{owner}/{repo}",
            "gitea://repos/{owner}/{repo}/readme",
            "gitea://repos/{owner}/{repo}/issues",
            "gitea://repos/{owner}/{repo}/issues/open",
            "gitea://repos/{owner}/{repo}/issues/closed",
            "gitea://repos/{owner}/{repo}/pulls",
            "gitea://repos/{owner}/{repo}/pulls/open",
            "gitea://repos/{owner}/{repo}/files/{path}",
            "gitea://repos/{owner}/{repo}/releases",
            "gitea://users/{username}",
            "gitea://orgs/{orgname}",
        ]
        for template in expected:
            assert template in uri_templates


class TestResourceFormatters:
    """Tests for other formatting functions."""

    def test_format_issues_markdown_empty(self):
        """Test empty issues list."""
        from gitea_mcp_server.resources import _format_issues_markdown

        result = _format_issues_markdown([], title="Test Issues")
        assert "# Test Issues" in result
        assert "No issues found." in result

    def test_format_pulls_markdown_with_data(self):
        """Test pull request formatting."""
        from gitea_mcp_server.resources import _format_pulls_markdown

        pull = {
            "number": 1,
            "title": "Test PR",
            "state": "open",
            "user": {"login": "contributor"},
            "created_at": "2024-01-01T00:00:00Z",
            "base": {"label": "main"},
            "head": {"label": "feature"},
            "comments": 5,
            "html_url": "https://example.com/pr/1",
        }
        result = _format_pulls_markdown([pull])

        assert "# Pull Requests" in result
        assert "## PR #1: Test PR" in result
        assert "**State**: open" in result
        assert "**Base**: main" in result

    def test_format_user_markdown_regular_user(self):
        """Test user profile formatting."""
        from gitea_mcp_server.resources import _format_user_markdown

        user = {
            "login": "johndoe",
            "full_name": "John Doe",
            "html_url": "https://example.com/johndoe",
            "public_repos": 10,
            "followers_count": 5,
            "following_count": 3,
            "created_at": "2024-01-01T00:00:00Z",
            "bio": "Software developer",
            "location": "NYC",
            "website": "https://johndoe.com",
        }
        result = _format_user_markdown(user)

        assert "# johndoe" in result
        assert "**Name**: John Doe" in result
        assert "| Public Repos | 10 |" in result
        assert "**Bio**: Software developer" in result

    def test_format_user_markdown_organization(self):
        """Test organization profile formatting."""
        from gitea_mcp_server.resources import _format_user_markdown

        org = {
            "login": "myorg",
            "type": "Organization",
            "html_url": "https://example.com/myorg",
            "public_repos": 25,
            "description": "A test organization",
        }
        result = _format_user_markdown(org)

        assert "# myorg" in result
        assert "| Type | Organization |" in result


class TestGetReadme:
    """Tests for get_readme function."""

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_base64_content(self, mock_gitea_client):
        """Test README with base64 encoded content."""
        # Prepare base64 encoded content
        readme_content = "# Test README\n\nThis is a test."
        encoded_content = base64.b64encode(readme_content.encode("utf-8")).decode("utf-8")

        mock_gitea_client.request = AsyncMock(
            return_value={"content": encoded_content, "encoding": "base64"}
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content
        mock_gitea_client.request.assert_called_once_with("GET", "/repos/owner/repo/readme")

    async def test_plain_text_content(self, mock_gitea_client):
        """Test README with plain text content (no base64 encoding)."""
        readme_content = "# Plain README\n\nNo encoding."

        mock_gitea_client.request = AsyncMock(
            return_value={
                "content": readme_content,
                "encoding": "text",  # or any non-base64 encoding
            }
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content

    async def test_missing_content_field(self, mock_gitea_client):
        """Test README response with missing content field."""
        mock_gitea_client.request = AsyncMock(
            return_value={
                "encoding": "base64"
                # content field is missing
            }
        )

        result = await get_readme("owner", "repo", mock_gitea_client)

        # Should return empty string when content is missing
        assert result == ""

    async def test_string_response(self, mock_gitea_client):
        """Test README when API returns a string directly."""
        readme_content = "# Direct string README"

        mock_gitea_client.request = AsyncMock(return_value=readme_content)

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == readme_content

    async def test_404_error(self, mock_gitea_client):
        """Test README raises ResourceError with NOT_FOUND on 404."""

        # Create an exception with status_code attribute
        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(404))

        with pytest.raises(ResourceError) as exc_info:
            await get_readme("owner", "repo", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "README not found" in error_data["message"]
        assert error_data["resource_type"] == "readme"
        assert error_data["resource_id"] == "owner/repo"

    async def test_other_errors_raised(self, mock_gitea_client):
        """Test that non-404 errors are raised."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(500))

        with pytest.raises(GiteaAPIError) as exc_info:
            await get_readme("owner", "repo", mock_gitea_client)

        assert exc_info.value.status_code == 500

    async def test_non_dict_non_string_response(self, mock_gitea_client):
        """Test handling of unexpected response types."""
        mock_gitea_client.request = AsyncMock(return_value=12345)

        result = await get_readme("owner", "repo", mock_gitea_client)

        assert result == "12345"


class TestCustomResourceErrorHandling:
    """Tests for custom resource error handling."""

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_get_repository_404_raises_resource_error(self, mock_gitea_client):
        """Test get_repository raises ResourceError with NOT_FOUND on 404."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(404))

        with pytest.raises(ResourceError) as exc_info:
            await get_repository("owner", "repo", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Repository 'owner/repo' not found" in error_data["message"]
        assert error_data["resource_type"] == "repository"
        assert error_data["resource_id"] == "owner/repo"

    async def test_get_file_404_raises_resource_error(self, mock_gitea_client):
        """Test get_file raises ResourceError with NOT_FOUND on 404."""

        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(404))

        with pytest.raises(ResourceError) as exc_info:
            await get_file("owner", "repo", "path/to/file", mock_gitea_client)

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "File 'path/to/file' not found" in error_data["message"]
        assert error_data["resource_type"] == "file"
        assert error_data["resource_id"] == "owner/repo/path/to/file"

    async def test_list_repo_issues_invalid_state_raises_validation_error(self, mock_gitea_client):
        """Test list_repo_issues raises ResourceError with VALIDATION_ERROR for invalid state."""

        with pytest.raises(ResourceError) as exc_info:
            await list_repo_issues("owner", "repo", mock_gitea_client, state="invalid")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "VALIDATION_ERROR"
        assert "Invalid state parameter: 'invalid'" in error_data["message"]
        assert error_data["resource_type"] == "issues"
        assert error_data["resource_id"] == "owner/repo"


class TestAutoGeneratedResourceErrors:
    """Tests for auto-generated resource error handling."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock FastMCP instance."""
        mcp = MagicMock(spec=FastMCP)
        return mcp

    @pytest.fixture
    def mock_gitea_client(self):
        """Create a mock GiteaClient."""
        client = AsyncMock()
        return client

    async def test_404_raises_structured_error(self, mock_mcp, mock_gitea_client):
        """Test auto-generated resource raises ResourceError with proper structure on 404."""
        spec = {
            "paths": {
                "/test/{id}": {
                    "get": {
                        "summary": "Test endpoint",
                        "operationId": "testEndpoint",
                        "parameters": [
                            {
                                "name": "id",
                                "in": "path",
                                "required": True,
                                "schema": {"type": "string"},
                            }
                        ],
                    }
                }
            }
        }

        # Track registered functions
        registered = []

        def track_decorator(uri):
            def decorator(func):
                registered.append((uri, func))
                return func

            return decorator

        mock_mcp.resource = MagicMock(side_effect=track_decorator)

        register_auto_generated_resources(mock_mcp, mock_gitea_client, spec, skip_uris=set())

        assert len(registered) == 1
        uri, resource_func = registered[0]
        assert uri == "gitea://test/{id}"

        # Simulate 404 error from client
        class GiteaAPIError(Exception):
            def __init__(self, status_code):
                self.status_code = status_code
                super().__init__(f"HTTP {status_code}")

        mock_gitea_client.request = AsyncMock(side_effect=GiteaAPIError(404))

        with pytest.raises(ResourceError) as exc_info:
            await resource_func(id="123")

        error_data = exc_info.value.args[0]
        assert error_data["code"] == "NOT_FOUND"
        assert "Resource not found: /test/123" in error_data["message"]
        assert error_data["resource_type"] == "api"
        assert error_data["resource_id"] == "/test/123"
