"""Tests for gitea_mcp_server.tools.contract — the generic contract spine.

The spine (:func:`~gitea_mcp_server.tools.contract.build_transform_fn`) is
shared by autogenerated and synthetic tools.  These tests exercise it with a
recording executor, independent of any specific backend: virtual-param
extraction, pre-hooks, context resolution, ``_raw_schema`` attachment, and
post-hook formatting.
"""

from __future__ import annotations

import base64
from typing import TYPE_CHECKING, Any
from unittest.mock import AsyncMock, patch

import pytest
from fastmcp.tools.base import Tool, ToolResult

from gitea_mcp_server.context_utils import safe_ctx_info
from gitea_mcp_server.tools.contract import (
    PROGRESS_COMPLETE,
    PROGRESS_START,
    PROGRESS_TOTAL,
    build_transform_fn,
)
from gitea_mcp_server.tools.result_pipeline import ExecutionResult
from gitea_mcp_server.tools.virtual_params import INERT_KEY
from tests.helpers.progress import RecordingContext
from tests.helpers.registration import autogen_meta
from tests.helpers.spec_fixtures import make_openapi_spec

if TYPE_CHECKING:
    from gitea_mcp_server.models import ViewHints


def _make_tool(
    *,
    raw_schema: dict[str, Any] | None = None,
    response_type: str | None = None,
    view_hints: ViewHints | None = None,
    injected: set[str] | frozenset[str] | None = frozenset({"format", "detail"}),
) -> Tool:
    """Minimal Tool whose record optionally carries display pipeline metadata.

    ``injected`` defaults to a finalised record (what the exposure seam stamps
    for a minimal autogen tool); pass ``None`` to leave the record pending.
    """
    return Tool(
        name="test_tool",
        description="A test tool.",
        parameters={"properties": {}},
        meta=autogen_meta(
            output_schema_raw=raw_schema,
            response_type=response_type,
            view_hints=view_hints,
            injected=injected,
        ),
    )


class TestBuildTransformFn:
    """Tests for the generic per-call contract spine."""

    @pytest.mark.asyncio
    async def test_executor_receives_popped_kwargs_and_extracted(self) -> None:
        """Virtual params are popped from kwargs and passed to the executor."""
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool()
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        result = await transform_fn(query="q", page=1, format="json", detail="full")

        assert received["kwargs"] == {"query": "q", "page": 1}
        assert received["extracted"] == {"format": "json", "detail": "full"}
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_spine_stamps_inert_once_on_extracted(self) -> None:
        """The spine derives the inert set once and stamps it for the executor.

        The executor consumes the stamped set as data; it never re-derives it.
        The key is absent when nothing is neutralized (the consumers' default).
        """
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            captured["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool(injected=frozenset({"format", "detail", "fetch_all"}))
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")

        await transform_fn(query="q", format="json", fetch_all=True)
        assert captured["extracted"][INERT_KEY] == frozenset({"page", "limit"})

        await transform_fn(query="q", format="json")
        assert INERT_KEY not in captured["extracted"]

    @pytest.mark.asyncio
    async def test_context_is_none_outside_session(self) -> None:
        """Executor receives ctx=None when no MCP session is active."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            captured["ctx"] = ctx
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(query="q")

        assert captured["ctx"] is None

    @pytest.mark.asyncio
    async def test_pre_hooks_mutate_kwargs(self) -> None:
        """Pre-hooks run before the executor (content_type base64-encodes content)."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            captured["content"] = kwargs.get("content")
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool(injected=frozenset({"format", "detail", "content_type"}))
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        await transform_fn(content="hello", content_type="text")

        assert captured["content"] == base64.b64encode(b"hello").decode()

    @pytest.mark.asyncio
    async def test_invalid_format_rejected_before_executor(self) -> None:
        """An invalid ``format`` fails before the executor — no side effect (#789)."""
        calls = {"n": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["n"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with pytest.raises(ValueError, match="format must be one of"):
            await transform_fn(query="q", format="bogus")

        assert calls["n"] == 0

    @pytest.mark.asyncio
    async def test_invalid_detail_rejected_before_executor(self) -> None:
        """An invalid ``detail`` fails before the executor (#789)."""
        calls = {"n": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["n"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with pytest.raises(ValueError, match="detail must be one of"):
            await transform_fn(query="q", detail="bogus")

        assert calls["n"] == 0

    @pytest.mark.asyncio
    async def test_invalid_content_type_rejected_before_pre_hook(self, monkeypatch: Any) -> None:
        """A bad ``content_type`` is rejected before the pre-hook encodes content.

        Asserts neither the executor nor the pre-hook stage is reached, so the
        rejection genuinely happens before ``content`` could be encoded.
        """
        calls = {"executor": 0, "pre_hooks": 0}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls["executor"] += 1
            return ExecutionResult(data="ok", shape="scalar")

        def _spy_pre_hooks(extracted: dict[str, Any], kwargs: dict[str, Any] | None = None) -> None:
            calls["pre_hooks"] += 1

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_pre_hooks", _spy_pre_hooks)

        tool = _make_tool(injected=frozenset({"format", "detail", "content_type"}))
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        with pytest.raises(ValueError, match="content_type must be one of"):
            await transform_fn(content="hello", content_type="bogus")

        assert calls == {"executor": 0, "pre_hooks": 0}

    @pytest.mark.asyncio
    async def test_absent_format_uses_spine_default(self) -> None:
        """When ``format`` is omitted, the configured default renders the result."""
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="json")
        result = await transform_fn(query="q")

        assert "format" not in received["extracted"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_raw_schema_attached_for_post_hooks(self, monkeypatch: Any) -> None:
        """The record's ``output_schema_raw`` reaches the post-hook as _raw_schema."""
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}
        seen: dict[str, Any] = {}

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            seen["extracted"] = dict(extracted)
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data={"name": "x"}, shape="object")

        transform_fn = build_transform_fn(
            _make_tool(raw_schema=raw_schema), executor, default_format="markdown"
        )
        await transform_fn(query="q")

        assert seen["extracted"]["_raw_schema"] == raw_schema

    @pytest.mark.asyncio
    async def test_post_hooks_run_after_executor(self, monkeypatch: Any) -> None:
        """apply_to receives the executor's result and its return value is the tool result."""
        calls: list[str] = []

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            calls.append("executor")
            return ExecutionResult(data="ok", shape="scalar")

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            calls.append("apply_to")
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        result = await transform_fn(query="q")

        assert calls == ["executor", "apply_to"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_allowlist_restricts_extraction(self) -> None:
        """The record's ``virtual_params`` limits which registry params are popped.

        Off-allowlist registry-name keys (e.g. ``fetch_all`` on a format-only
        synthetic tool) stay in kwargs so validation rejects them as unknown
        instead of silently dropping the value.
        """
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool(injected=frozenset({"format"}))
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        await transform_fn(query="q", format="json", fetch_all=True)

        # format (allowlisted) popped; fetch_all (off-allowlist) left in kwargs.
        assert received["extracted"] == {"format": "json"}
        assert received["kwargs"] == {"query": "q", "fetch_all": True}

    @pytest.mark.asyncio
    async def test_unfinalised_record_is_rejected(self) -> None:
        """The spine refuses a pending (un-finalised) registration record.

        The retired "no allowlist stamped → pop every registry param" fallback
        is gone: every exposed tool is finalised at the exposure seam, so a
        record without a resolved ``virtual_params`` is a programming error —
        never a silent pop-all.
        """

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        tool = _make_tool(injected=None)
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        with pytest.raises(ValueError, match="not finalised"):
            await transform_fn(query="q", format="json", fetch_all=True)

    @pytest.mark.asyncio
    async def test_missing_record_is_rejected(self) -> None:
        """The spine refuses a tool that carries no registration record."""

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        tool = Tool(
            name="unregistered",
            description="An unregistered tool.",
            parameters={"properties": {}},
            meta={},
        )
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        with pytest.raises(ValueError, match="has no registration record"):
            await transform_fn(query="q")

    @pytest.mark.asyncio
    async def test_autogen_allowlist_leaves_fetch_all_in_kwargs(self) -> None:
        """Autogen tools' resolved allowlist excludes fetch_all → rejected as unknown.

        ``_inject_params`` finalises the record's ``virtual_params`` with the
        actually-injected set (fetch_all is predicate-gated to synthetic
        tools), so extraction leaves it in kwargs for validation to reject
        instead of silently dropping it.
        """
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ExecutionResult(data="ok", shape="scalar")

        # What _inject_params stamps for an autogen tool: visible params that
        # passed injection (format/detail), fetch_all excluded by predicate.
        tool = _make_tool(injected=frozenset({"format", "detail"}))
        transform_fn = build_transform_fn(tool, executor, default_format="markdown")
        await transform_fn(query="q", format="json", fetch_all=True)

        assert received["extracted"] == {"format": "json"}
        assert received["kwargs"] == {"query": "q", "fetch_all": True}

    @pytest.mark.asyncio
    async def test_openapi_spec_forwarded_to_render(self, monkeypatch: Any) -> None:
        """build_transform_fn captures openapi_spec and threads it to render (#759).

        The spec enables root-list item summaries under ``detail=concise``.
        This is the unit lock for the closure threading — without it the
        wiring (``mcp_builder`` → ``build_transform_fn`` → ``render`` →
        collapse) is pinned only by the live suite.
        """
        from gitea_mcp_server.tools import contract as contract_module

        spec = make_openapi_spec()
        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch.setattr(contract_module, "render", _spy_render)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(
            _make_tool(), executor, openapi_spec=spec, default_format="markdown"
        )
        result = await transform_fn(query="q", format="json")

        assert seen["openapi_spec"] is spec
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_openapi_spec_defaults_to_none(self, monkeypatch: Any) -> None:
        """Omitting the spec (unit callers) forwards ``None`` — fallback contract."""
        from gitea_mcp_server.tools import contract as contract_module

        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch.setattr(contract_module, "render", _spy_render)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        await transform_fn(query="q", format="json")

        assert seen["openapi_spec"] is None

    @pytest.mark.asyncio
    async def test_execution_result_is_rendered_by_pipeline(self) -> None:
        """Every executor return is rendered by the single result pipeline.

        There is no ToolResult carve-out: the spine renders the executor's
        ``ExecutionResult`` through the pipeline, so ``format=json`` produces
        the envelope in the text channel.
        """
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ExecutionResult:
            return ExecutionResult(data={"name": "alpha"}, shape="object")

        transform_fn = build_transform_fn(
            _make_tool(raw_schema=raw_schema), executor, default_format="markdown"
        )
        result = await transform_fn(query="q", format="json")

        assert result.structured_content == {"result": {"name": "alpha"}}


class TestDisplayExtraDerivation:
    """The spine forwards formatter context derived from the call args.

    ``owner``/``repo``/``type`` are real path/query params on the tools whose
    domain formatters use them; the spine surfaces them as the pipeline's
    ``extra`` display input — the same channel as the page/limit capture.
    """

    @staticmethod
    async def _run_transform(
        *,
        tool: Tool | None = None,
        **call_kwargs: Any,
    ) -> dict[str, Any]:
        """Run the spine with a spy on ``render``; return the captured kwargs."""
        from gitea_mcp_server.tools import contract as contract_module

        seen: dict[str, Any] = {}
        real_render = contract_module.render

        def _spy_render(result: ExecutionResult, **kwargs: Any) -> ToolResult:
            seen.update(kwargs)
            return real_render(result, **kwargs)

        monkeypatch = pytest.MonkeyPatch()
        try:
            monkeypatch.setattr(contract_module, "render", _spy_render)

            async def executor(
                kwargs: dict[str, Any],
                extracted: dict[str, Any] | None,
                ctx: Any,
            ) -> ExecutionResult:
                return ExecutionResult(data=[], shape="list")

            transform_fn = build_transform_fn(
                tool or _make_tool(), executor, default_format="markdown"
            )
            await transform_fn(**call_kwargs)
            return seen
        finally:
            monkeypatch.undo()

    @pytest.mark.asyncio
    async def test_context_keys_forwarded(self) -> None:
        seen = await self._run_transform(owner="o", repo="r", type="pulls", format="json")
        assert seen["extra"] == {"owner": "o", "repo": "r", "type": "pulls"}

    @pytest.mark.asyncio
    async def test_org_context_key_forwarded(self) -> None:
        """Org-scoped tools forward ``org`` as display context (#766)."""
        seen = await self._run_transform(org="mcp-server", format="json")
        assert seen["extra"] == {"org": "mcp-server"}

    @pytest.mark.asyncio
    async def test_partial_context_keys(self) -> None:
        seen = await self._run_transform(owner="o", q="x", format="json")
        assert seen["extra"] == {"owner": "o"}

    @pytest.mark.asyncio
    async def test_no_context_keys_is_none(self) -> None:
        """Tools without repo scope pass ``None`` — formatters use graceful defaults."""
        seen = await self._run_transform(q="x", format="json")
        assert seen["extra"] is None

    @pytest.mark.asyncio
    async def test_response_type_forwarded_from_tool_meta(self) -> None:
        """The spine reads the record's ``response_type`` into ``render``."""
        seen = await self._run_transform(tool=_make_tool(response_type="Repository"), format="json")
        assert seen["response_type"] == "Repository"

    @pytest.mark.asyncio
    async def test_view_hints_forwarded_from_tool_meta(self) -> None:
        """The spine reads the record's ``view_hints`` into ``render`` (#775)."""
        hints: ViewHints = {"omit": ["url"]}
        seen = await self._run_transform(
            tool=_make_tool(response_type="Repository", view_hints=hints), format="json"
        )
        assert seen["view_hints"] == hints

    @pytest.mark.asyncio
    async def test_absent_view_hints_is_none(self) -> None:
        """A tool without view hints in its record passes ``None`` — plain schema view."""
        seen = await self._run_transform(format="json")
        assert seen["view_hints"] is None

    @pytest.mark.asyncio
    async def test_absent_response_type_is_none(self) -> None:
        """A tool without a response type in its record passes ``None`` — generic renderer."""
        seen = await self._run_transform(format="json")
        assert seen["response_type"] is None

    def test_none_values_dropped(self) -> None:
        """A param explicitly set to ``None`` is not forwarded as context."""
        from gitea_mcp_server.tools.contract import _derive_display_extra

        assert _derive_display_extra({"owner": "o", "repo": None}) == {"owner": "o"}
        assert _derive_display_extra({"owner": None}) is None
        assert _derive_display_extra({}) is None


def _result_for_shape(shape: str) -> ExecutionResult:
    """Return a render-valid ``ExecutionResult`` for one of the six shapes.

    The payload matches what :func:`render` expects per shape (binary carries
    ``content_info``, empty carries ``message``, list/object carry structured
    ``data``) so the parametrized test exercises the lifecycle, not render's
    error-recovery path.
    """
    if shape == "empty":
        return ExecutionResult(
            data=None, shape="empty", message="Operation completed successfully."
        )
    if shape == "binary":
        return ExecutionResult(data={"content_type": "application/zip", "size": 3}, shape="binary")
    if shape == "text":
        return ExecutionResult(data="raw text", shape="text")
    if shape == "scalar":
        return ExecutionResult(data=42, shape="scalar")
    if shape == "list":
        return ExecutionResult(data=[{"id": 1}], total_count=1, shape="list", paginated=True)
    return ExecutionResult(data={"k": "v"}, shape="object")


class TestProgressLifecycle:
    """The contract spine owns the MCP progress lifecycle (#825).

    The spine emits a start signal before the executor and a terminal signal
    after a successful render; executors never emit progress.  A recording
    executor exercises the spine directly — autogen and synthetic tools are
    both "an executor" at this seam.
    """

    @pytest.mark.asyncio
    async def test_start_executor_terminal_in_order(self) -> None:
        """The spine emits start, runs the executor, then emits terminal."""
        ctx = RecordingContext()

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ctx.mark("executor")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with patch(
            "gitea_mcp_server.tools.contract.resolve_current_context",
            new=AsyncMock(return_value=ctx),
        ):
            result = await transform_fn(query="q")

        assert result.structured_content == {"result": "ok"}
        assert ctx.calls == [
            ("progress", PROGRESS_START, PROGRESS_TOTAL),
            ("mark", "executor"),
            ("progress", PROGRESS_COMPLETE, PROGRESS_TOTAL),
        ]

    @pytest.mark.parametrize("shape", ["scalar", "object", "list", "text", "empty", "binary"])
    @pytest.mark.asyncio
    async def test_lifecycle_is_shape_independent(self, shape: str) -> None:
        """Every result shape gets the same start + terminal signals.

        The historical bug was the autogen executor skipping the terminal on
        its early-return response classes; the spine must not branch on shape.
        """
        ctx = RecordingContext()

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ctx.mark("executor")
            return _result_for_shape(shape)

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with patch(
            "gitea_mcp_server.tools.contract.resolve_current_context",
            new=AsyncMock(return_value=ctx),
        ):
            await transform_fn(query="q")

        assert ctx.calls[0] == ("progress", PROGRESS_START, PROGRESS_TOTAL)
        assert ctx.calls[-1] == ("progress", PROGRESS_COMPLETE, PROGRESS_TOTAL)
        assert ("mark", "executor") in ctx.calls

    @pytest.mark.asyncio
    async def test_no_terminal_when_executor_raises(self) -> None:
        """An errored executor emits the start but never claims completion."""
        ctx = RecordingContext()

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ctx.mark("executor")
            msg = "boom"
            raise ValueError(msg)

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with (
            patch(
                "gitea_mcp_server.tools.contract.resolve_current_context",
                new=AsyncMock(return_value=ctx),
            ),
            pytest.raises(ValueError, match="boom"),
        ):
            await transform_fn(query="q")

        assert ctx.calls == [
            ("progress", PROGRESS_START, PROGRESS_TOTAL),
            ("mark", "executor"),
        ]

    @pytest.mark.asyncio
    async def test_no_terminal_when_render_raises(self) -> None:
        """A failed render emits the start but never claims completion."""
        ctx = RecordingContext()

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ctx.mark("executor")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with (
            patch(
                "gitea_mcp_server.tools.contract.resolve_current_context",
                new=AsyncMock(return_value=ctx),
            ),
            patch(
                "gitea_mcp_server.tools.contract.render",
                side_effect=ValueError("render boom"),
            ),
            pytest.raises(ValueError, match="render boom"),
        ):
            await transform_fn(query="q")

        assert ctx.calls == [
            ("progress", PROGRESS_START, PROGRESS_TOTAL),
            ("mark", "executor"),
        ]

    @pytest.mark.asyncio
    async def test_no_session_is_noop(self) -> None:
        """Outside a session (ctx=None) the lifecycle degrades to no-ops."""
        ran: list[str] = []

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ran.append("executor")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        result = await transform_fn(query="q")

        assert ran == ["executor"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_progress_failure_does_not_abort_the_call(self) -> None:
        """A client/transport progress failure never aborts the call (#827).

        Both the start and the terminal signal fail; the spine swallows each
        and still returns the rendered result.
        """
        ctx = AsyncMock()
        ctx.report_progress.side_effect = ValueError("client progress handler failed")
        ran: list[str] = []

        async def executor(kwargs: Any, extracted: Any, _ctx: Any) -> ExecutionResult:
            ran.append("executor")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with patch(
            "gitea_mcp_server.tools.contract.resolve_current_context",
            new=AsyncMock(return_value=ctx),
        ):
            result = await transform_fn(query="q")

        assert ran == ["executor"]
        assert result.structured_content == {"result": "ok"}
        assert ctx.report_progress.await_count == 2

    @pytest.mark.asyncio
    async def test_executor_log_failure_does_not_abort_the_call(self) -> None:
        """An executor's ``safe_ctx_info`` failure never aborts the call (#827).

        Executors log breadcrumbs through ``safe_ctx_info``; a failing
        ``ctx.info`` there must not abort — the ``safe_ctx_info`` half of the
        class.
        """
        ctx = AsyncMock()
        ctx.info.side_effect = ValueError("client log handler failed")

        async def executor(kwargs: Any, extracted: Any, ctx_arg: Any) -> ExecutionResult:
            # A real executor logs its route/breadcrumb through the safe helper.
            await safe_ctx_info(ctx_arg, "route: GET /version")
            return ExecutionResult(data="ok", shape="scalar")

        transform_fn = build_transform_fn(_make_tool(), executor, default_format="markdown")
        with patch(
            "gitea_mcp_server.tools.contract.resolve_current_context",
            new=AsyncMock(return_value=ctx),
        ):
            result = await transform_fn(query="q")

        assert result.structured_content == {"result": "ok"}
