"""Tests for gitea_mcp_server.tools.contract — the generic contract spine.

The spine (:func:`~gitea_mcp_server.tools.contract.build_transform_fn`) is
shared by autogenerated and synthetic tools.  These tests exercise it with a
recording executor, independent of any specific backend: virtual-param
extraction, pre-hooks, context resolution, ``_raw_schema`` attachment, and
post-hook formatting.
"""

from __future__ import annotations

import base64
from typing import Any

import pytest
from fastmcp.tools.base import Tool, ToolResult
from mcp.types import TextContent

from gitea_mcp_server.tools.contract import build_transform_fn


def _make_tool(*, raw_schema: dict[str, Any] | None = None) -> Tool:
    """Minimal Tool whose meta optionally carries ``output_schema_raw``."""
    meta: dict[str, Any] = {}
    if raw_schema is not None:
        meta["output_schema_raw"] = raw_schema
    return Tool(
        name="test_tool",
        description="A test tool.",
        parameters={"properties": {}},
        meta=meta,
    )


class TestBuildTransformFn:
    """Tests for the generic per-call contract spine."""

    @pytest.mark.asyncio
    async def test_executor_receives_popped_kwargs_and_extracted(self) -> None:
        """Virtual params are popped from kwargs and passed to the executor."""
        received: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            received["kwargs"] = dict(kwargs)
            received["extracted"] = dict(extracted or {})
            return ToolResult(structured_content={"result": "ok"})

        tool = _make_tool()
        transform_fn = build_transform_fn(tool, executor)
        result = await transform_fn(query="q", page=1, format="json", detail="full")

        assert received["kwargs"] == {"query": "q", "page": 1}
        assert received["extracted"] == {"format": "json", "detail": "full"}
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_context_is_none_outside_session(self) -> None:
        """Executor receives ctx=None when no MCP session is active."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            captured["ctx"] = ctx
            return ToolResult(structured_content={"result": "ok"})

        transform_fn = build_transform_fn(_make_tool(), executor)
        await transform_fn(query="q")

        assert captured["ctx"] is None

    @pytest.mark.asyncio
    async def test_pre_hooks_mutate_kwargs(self) -> None:
        """Pre-hooks run before the executor (content_type base64-encodes content)."""
        captured: dict[str, Any] = {}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            captured["content"] = kwargs.get("content")
            return ToolResult(structured_content={"result": "ok"})

        transform_fn = build_transform_fn(_make_tool(), executor)
        await transform_fn(content="hello", content_type="text")

        assert captured["content"] == base64.b64encode(b"hello").decode()

    @pytest.mark.asyncio
    async def test_raw_schema_attached_for_post_hooks(self, monkeypatch: Any) -> None:
        """tool.meta['output_schema_raw'] reaches the post-hook as _raw_schema."""
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}
        seen: dict[str, Any] = {}

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            seen["extracted"] = dict(extracted)
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            return ToolResult(structured_content={"result": {"name": "x"}})

        transform_fn = build_transform_fn(_make_tool(raw_schema=raw_schema), executor)
        await transform_fn(query="q")

        assert seen["extracted"]["_raw_schema"] == raw_schema

    @pytest.mark.asyncio
    async def test_post_hooks_run_after_executor(self, monkeypatch: Any) -> None:
        """apply_to receives the executor's result and its return value is the tool result."""
        calls: list[str] = []

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            calls.append("executor")
            return ToolResult(structured_content={"result": "ok"})

        def _spy_apply_to(result: ToolResult, extracted: dict[str, Any]) -> ToolResult:
            calls.append("apply_to")
            return result

        monkeypatch.setattr("gitea_mcp_server.tools.contract.apply_to", _spy_apply_to)

        transform_fn = build_transform_fn(_make_tool(), executor)
        result = await transform_fn(query="q")

        assert calls == ["executor", "apply_to"]
        assert result.structured_content == {"result": "ok"}

    @pytest.mark.asyncio
    async def test_real_format_post_hook_renders_content(self) -> None:
        """End-to-end: the registered format post-hook renders structured data to text."""
        raw_schema = {"type": "object", "properties": {"name": {"type": "string"}}}

        async def executor(
            kwargs: dict[str, Any],
            extracted: dict[str, Any] | None,
            ctx: Any,
        ) -> ToolResult:
            return ToolResult(structured_content={"result": {"name": "alpha"}})

        transform_fn = build_transform_fn(_make_tool(raw_schema=raw_schema), executor)
        result = await transform_fn(query="q", format="json")

        text = next(c.text for c in result.content if isinstance(c, TextContent))
        assert '"name": "alpha"' in text
        # structured_content carries the uncollapsed data for programmatic access.
        assert result.structured_content == {"result": {"name": "alpha"}}
